# FOSSology Makefile configuration
# Copyright (C) 2009 Hewlett-Packard Development Company, L.P.
# 
# This file contains the default values for variables used in the
# Makefiles and other locations in the source tree.
# If you want different values, you can override them on
# the make command line. For example
#    'make VERSION=0.8.0.beta3 all'
# changing them here is probably a bad idea, try to use the above

#####################################################################
# Project info
#####################################################################
# the name of our project
PROJECT=fossology

# the version of our project
# use the version with a date, when a build script is written to update it or 
# when packages are made on an infrequent basis during development
VERSION=2.0~devel

# user for the project
PROJECTUSER=fossy

# group for the project
PROJECTGROUP=$(PROJECTUSER)

#####################################################################
# Install paths
#####################################################################
# pseudoroot for packaging purposes
DESTDIR=

# base of the program data tree
PREFIX=/usr/local

# executable programs that users run
BINDIR=$(PREFIX)/bin

# executable programs that sysadmins run
SBINDIR=$(PREFIX)/sbin

# config files
SYSCONFDIR=$(PREFIX)/etc

# init script root dir
INITDIR=/etc

# object code libraries
LIBDIR=$(PREFIX)/lib

# header files
INCLUDEDIR=$(PREFIX)/include

# executables/libraries that only our project uses
LIBEXECDIR=$(PREFIX)/lib/$(PROJECT)

# non-arch-specific data
DATAROOTDIR=$(PREFIX)/share

# non-arch-dependent program data
DATADIR=$(DATAROOTDIR)/$(PROJECT)

# hardcoded repo location, eventually this will be determined at runtime
REPODIR=/srv/$(PROJECT)/repository

# local state
LOCALSTATEDIR=/var/local

# project local state
PROJECTSTATEDIR=$(LOCALSTATEDIR)/lib/$(PROJECT)

# project logdir
LOGDIR=/var/log/$(PROJECT)

# man pages
MANDIR=$(DATAROOTDIR)/man

# Man pages in *roff format, man 1
MAN1DIR=$(MANDIR)/man1

# project documentation
DOCDIR=$(DATAROOTDIR)/doc/$(PROJECT)

# webroot
WEBDIR=$(DATADIR)/www

# php root
PHPDIR=$(DATADIR)/php

#####################################################################
# Agent install paths
#####################################################################
# arch-specific agent subdirs
AGENTDIR=$(LIBEXECDIR)/agents

# non-arch-specific agent subdirs
AGENTDATADIR=$(DATADIR)/agents

# agent runtime data
AGENTSTATEDIR=$(PROJECTSTATEDIR)/agents

#####################################################################
# Build variables
#####################################################################
SHELL = /bin/sh
CC=gcc
INSTALL = /usr/bin/install -D
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA = ${INSTALL} -m 644

# if this ends up running in a non svn dir, like for example someone
# doing a build from a release tarball, the result returned is "exported"
# meaning the tree was exported from svn rather than a working copy,
# this is good. We also catch if they don't have svn.
SVN_REV:=$(shell svnversion -n . 2>&1 || echo "exported")

# these are the default cflags, recommended but not fully _required_
# if a user sets CFLAGS they get what they set it to and lose any they
# didn't include, which is the expected behavior
#CFLAGS=-O2 -Wall
CFLAGS=-g -O2 -Wall

# agent library
# $TOP is set in each Makefile in order to make these work
FOSRCDIR=$(TOP)/src
FOLIBDIR=$(FOSRCDIR)/lib/c
FOLIB=$(FOLIBDIR)/libfossology.a
CFLAGS_FO=-I`pg_config --includedir` `pkg-config glib-2.0 --cflags --libs` \
          -I$(FOLIBDIR) -L$(FOLIBDIR) -lfossology -lpq

# these are the required flags we don't want to go away if the user sets
# CFLAGS. note we _post_fix the existing CFLAGS in case the user wants to
# override stuff (GCS 7.2.3)
ALL_CFLAGS=-DSVN_REV='"$(VERSION), $(SVN_REV)"' $(CFLAGS) $(CFLAGS_FO)

# directory containing the php iPATHFILE include file
FOWWWDIR=$(FOSRCDIR)/www/ui

# pathname for the php iPATHFILE include file
iPATHFILE=$(FOWWWDIR)/pathinclude.php

# for use when coverage C code 
FLAG_COV=-fprofile-arcs -ftest-coverage
