######################################################################
# Copyright (C) 2011 Hewlett-Packard Development Company, L.P.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
######################################################################
all:
	@echo "Empty Directory: ...src/buckets/agent_tests; Nothing to make"
test:
	@echo "No bucket tests in ...src/buckets/agent_tests"
clean:
	@echo "Empty Directory: ...src/buckets/agent_tests; Nothing to clean"
install:
	@echo "Empty Directory: ...src/buckets/agent_tests; Nothing to install"
uninstall:
	@echo "Empty Directory: ...src/buckets/agent_tests; Nothing to uninstall"
