<?php
/***************************************************************
Copyright (C) 2017 Siemens AG
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 ***************************************************************/
/**
 * @namespace Fossology::DelAgent::UI
 * @brief UI namespace for delagent
 */
namespace Fossology\DelAgent\UI;

/**
 * @class DeleteMessages
 * @brief Messages which can be generated by delagent
 */
abstract class DeleteMessages
{
  const SCHEDULING_FAILED = 1; /**< Deletion Scheduling failed */
  const SUCCESS =  2; /**< Deletion added to job queue */
  const NO_PERMISSION = 3; /**< You don't have permissions to delete the upload */
}
