<?php
/*
 SPDX-FileCopyrightText: © 2017 Siemens AG

 SPDX-License-Identifier: GPL-2.0-only
*/
/**
 * @namespace Fossology::DelAgent::UI
 * @brief UI namespace for delagent
 */
namespace Fossology\DelAgent\UI;

/**
 * @class DeleteMessages
 * @brief Messages which can be generated by delagent
 */
abstract class DeleteMessages
{
  const SCHEDULING_FAILED = 1; /**< Deletion Scheduling failed */
  const SUCCESS =  2; /**< Deletion added to job queue */
  const NO_PERMISSION = 3; /**< You don't have permissions to delete the upload */
}
