#!/bin/bash
# SPDX-FileCopyrightText: © 2012 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

# check for fedora or red hat systems and cd to the appropriate place
# "$Id$"
#
echo "Node is:$NODE_NAME"
if [ "$NODE_NAME" = "" ]
then
  exit 0
fi

name=`expr match "$NODE_NAME" '\(.[fed|rhel].+\)'`

echo "name extracted is:$name"

