apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fossology
  namespace: argocd
spec:
  project: fossology
  source:
    repoURL: https://github.com/fossology/fossology
    targetRevision: HEAD
    path: kubernetes/helm/fossology
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fossology
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
