# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# original script by maximilian.huber@tngtech.com
# additions by michael.c.jaeger@siemens.com
#
# SPDX-License-Identifier: GPL-2.0
#
# this script starts a VM in order to run project builder inside
# for development and debugging
#

#
# std vagrant setup
#
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "3072"]
    vbox.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.synced_folder "..", "/home/vagrant/prj/fossology", type: "rsync"
  config.vm.network "forwarded_port", guest: 80, host: 8081

#
# part to prepare dependencies
#
  config.vm.provision "shell" do |s|
    s.inline = <<SCRIPT
set -ex

yum install -y wget git

# install EPEL
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm

# install composer
wget http://ftp.project-builder.org/centos/7/x86_64/pb.repo
cp pb.repo /etc/yum.repos.d/

# not using gpg checking is not recommended
# yum update -y --nogpgcheck
# yum install -y project-builder --nogpgcheck
yum update -y
yum install -y project-builder

# install build dependencies
yum install -y redhat-lsb
/home/vagrant/prj/fossology/utils/fo-installdeps -e -y

# adding docker install info for prepping the project builder installation runs
cat > /etc/yum.repos.d/docker.repo << EOF
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

# ... then installing docker
yum install -y docker-engine

# ... starting docker
systemctl start docker

SCRIPT
  end
  
#
# checking out and preparing project builder
# note that triple backslashes are because of cat and vagrant escaping
#
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline = <<SCRIPT
sudo chown vagrant:vagrant ~/prj
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

set -ex

################################################################################
# configure pb
cat<<PBRC > $HOME/.pbrc

pbdefdir default = \\\$ENV{HOME}/cache-project-builder
pbstoponerr default = true

pburl fossology = git+https://github.com/fossology/fossology.git
pbdefdir fossology =  \\\$ENV{'HOME'}/prj
pbconfurl fossology = git+https://github.com/fossology/fossology.git
pbconfdir fossology = \\\$ENV{'HOME'}/prj/fossology/pbconf

PBRC

################################################################################
# sbx = sandbox
# actually, sbx2pkg is included in sbx2pkg2ins
for pkg in "fossology-composer" "fossology"; do
    pb -t -p fossology sbx2build   $pkg
    pb -p    fossology build2prep  $pkg
#   pb -t -p fossology sbx2pkg     $pkg
    pb -t -p fossology sbx2pkg2ins $pkg
done

SCRIPT
  end
  
#
# applying some work around
#
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline = <<SCRIPT
    
# uahhh: disabling SELinux
# remove if the https://github.com/fossology/fossology/issues/727
setenforce 0

SCRIPT
  end

end