######################################################################
# Copyright (C) 2011 Hewlett-Packard Development Company, L.P.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
######################################################################

MOD_NAME=example_wc_agent
MOD_SUBDIR=ui

all:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR)"

test:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) test"

coverage:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) coverage"

clean:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) clean"

install:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) install"

uninstall:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) uninstall"

.PHONY: all test coverage clean install uninstall
