# SPDX-FileCopyrightText: © 2011 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

MOD_NAME=example_wc_agent
MOD_SUBDIR=ui

all:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR)"

test:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) test"

coverage:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) coverage"

clean:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) clean"

install:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) install"

uninstall:
	@echo "$make $(MOD_NAME)/$(MOD_SUBDIR) uninstall"

.PHONY: all test coverage clean install uninstall
