#!/bin/bash
#***********************************************************
# cp2foss.php
# Copyright (C) 2007 Hewlett-Packard Development Company, L.P.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
#51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#***********************************************************/
#
# install script for cp2foss tests MUST BE RUN AS ROOT
#
# version "$Id: $"

if [[ -x "/usr/local/bin/test.cp2foss" ]]
then
  :
else
  cp ../cp2foss.php /usr/local/bin/test.cp2foss
fi

# ensure owner and permissions are correct
chown fossy:fossy /usr/local/bin/test.cp2foss
chmod ug-w+rx /usr/local/bin/test.cp2foss
chmod o-wx+r /usr/local/bin/test.cp2foss

# copy archives to tmp

cp archives/* /tmp
