#!/bin/bash
# Copyright (C) 2012 Hewlett-Packard Development Company, L.P.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# check for fedora or red hat systems and cd to the appropriate place
# "$Id$"
#
echo "Node is:$NODE_NAME"
if [ "$NODE_NAME" = "" ]
then
  exit 0
fi

name=`expr match "$NODE_NAME" '\(.[fed|rhel].+\)'`

echo "name extracted is:$name"

