apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: POSTGRES_DB
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: POSTGRES_INITDB_ARGS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
          image: postgres:9.6
          ports:
            - containerPort: 5432
          name: db
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready --dbname $(POSTGRES_DB) --username $(POSTGRES_USER)
          #   failureThreshold: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
      restartPolicy: Always
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database
status:
  replicas: 1