apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: repository
  name: repository
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
