apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent
    agent.type: copyright
  name: copyright
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
      agent.type: copyright
  strategy: {}
  template:
    metadata:
      labels:
        app: agent
        agent.type: copyright
    spec:
      hostname: copyright
      subdomain: agent-svc
      containers:
        - args:
            - agent
            - copyright
          env:
            - name: FOSSOLOGY_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fossology
                  key: FOSSOLOGY_DB_HOST
            - name: FOSSOLOGY_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: POSTGRES_DB
            - name: FOSSOLOGY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: FOSSOLOGY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: FOSSOLOGY_SCHEDULER_HOST
              valueFrom:
                configMapKeyRef:
                  name: fossology
                  key: FOSSOLOGY_SCHEDULER_HOST
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: repository                               
          image: fossology/copyright:latest
          imagePullPolicy: Never
          name: copyright
          resources: {}
      restartPolicy: Always
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: repository            
status: {}
