######################################################################
# Copyright (C) 2011 Hewlett-Packard Development Company, L.P.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
######################################################################

#
# Makefile for nomos agent Unit tests

TOP = ../../../..
VARS = $(TOP)/Makefile.conf
include $(VARS)

#EXE=test_nomos

test:
	@echo "make nomos Unit agent_tests"
	echo "No Unit Tests for Nomos"
	
coverage:
	@echo "make copyright agent_tests coverage"
	echo "No Coverage tests for Nomos"
	
clean:
	echo "Make nomos clean"
	rm -rf $(EXE) *.a *.o *.g *.xml *.txt *.gcda *.gcno results

install:
	@echo "No installs for nomos ui_tests/Unit"

uninstall:
	@echo "No uninstalls for nomos ui_tests/Unit"

.PHONY: all test coverage clean
