# SPDX-FileCopyrightText: © 2011 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

# Makefile for nomos agent Unit tests

TOP = ../../../..
VARS = $(TOP)/Makefile.conf
include $(VARS)

#EXE=test_nomos

test:
	@echo "make nomos Unit agent_tests"
	echo "No Unit Tests for Nomos"

coverage:
	@echo "make copyright agent_tests coverage"
	echo "No Coverage tests for Nomos"

clean:
	echo "Make nomos clean"
	rm -rf $(EXE) *.a *.o *.g *.xml *.txt *.gcda *.gcno results

install:
	@echo "No installs for nomos ui_tests/Unit"

uninstall:
	@echo "No uninstalls for nomos ui_tests/Unit"

.PHONY: all test coverage clean
