# fosslic man page input file
# Copyright (C) 2007 Hewlett-Packard Development Company, L.P.
#
# VERSION: $Id: $
#

=head1 NAME

fosslic - Perform a license analyze on or more files.

=head1 SYNOPSIS

fosslic  fosslic [options] file [file [file...]]

=head1 DESCRIPTION

B<fosslic> is a limited command line fossology utility that can be used to
perform a fossology license analysis on the specified files.  B<fosslic> has
a number of limitations similar to the One-Shot user interface function.
The limitations are:

=over

=item *

The analysis is done in real-time. Large files may take a while.
This method is not recommended for files larger than a few hundred kilobytes.

=item *

Files that contain files are not unpacked. If you use a I<zip> or
I<deb> file, then the binary file will be scanned for licenses and nothing
will likely be found.

=item *

Prints a simple list that summarizes the identified license types.  The
One-Shot user interface function will display the same summary or provide a
color coded table and a highlighted listing of the licenses found.

=back

=head2 Options

=over

=item B<-h>

Standard help flag, prints usage.

=item B<-v>

Enable verbose debugging.

=back

=head2 Examples

Perform an analysis on a filed called somefile.

 $: fosslic /tmp/somefile

Produces:

 /tmp/somefile: LGPL v2.1 Preamble, LGPL v2.1+

=head1 Authors

Neal Krawetz


