# Copyright Siemens AG 2014
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

TOP = ../../../..
VARS = $(TOP)/Makefile.conf
DEPS = $(TOP)/Makefile.deps
include $(VARS)

all:
	@echo "nothing to do"

test:
	@echo "nothing to do"

coverage:
	@echo "nothing to do"

clean:
	@echo "nothing to do"

.PHONY: all test coverage clean

include $(DEPS)
