#!/usr/bin/env bash
# FOSSology mod_deps script for containeragent
# Installs runtime and buildtime dependencies.
#
# SPDX-FileCopyrightText: © 2026 Fossology contributors
# SPDX-License-Identifier: GPL-2.0-only

source "$(dirname ${BASH_SOURCE[0]})/../../utils/utils.sh"

YesOpt=''
EVERYTHING=''
RUNTIME=''
BUILDTIME=''

OPTS=$(getopt -o rbehy --long runtime,buildtime,everything,help \
       -n 'mod_deps' -- "$@")
if [[ $? -ne 0 ]]; then OPTS='--help'; fi

eval set -- "$OPTS"

if [[ $OPTS == ' --' || $OPTS == ' -y --' ]]; then
  EVERYTHING=true
fi

while true; do
  case "$1" in
    -r|--runtime)     RUNTIME=true;    shift ;;
    -b|--buildtime)   BUILDTIME=true;  shift ;;
    -e|--everything)  EVERYTHING=true; shift ;;
    -y)               YesOpt='-y';     shift ;;
    -h|--help)        show_help_for_mod_deps; exit ;;
    --)               shift; break ;;
    *)                echo "ERROR: option $1 not recognised"; exit 1 ;;
  esac
done

set -o errexit -o nounset -o pipefail

must_run_as_root
need_lsb_release

if [[ $EVERYTHING ]]; then
  echo "*** Installing both runtime and buildtime dependencies ***"
  RUNTIME=true
  BUILDTIME=true
fi

DISTRO=$(lsb_release --id --short)

########################################################################

if [[ $BUILDTIME ]]; then
  echo "*** Installing $DISTRO buildtime dependencies ***"
  case "$DISTRO" in
    Debian|Ubuntu|Tuxedo)
      apt-get $YesOpt install \
        libjson-c-dev \
        libsqlite3-dev \
	libarchive-dev
      ;;
    RedHatEnterprise*|CentOS|Fedora)
      yum $YesOpt install \
        json-c-devel \
        sqlite-devel \
	libarchive-devel
      ;;
  esac
fi

if [[ $RUNTIME ]]; then
  echo "*** Installing $DISTRO runtime dependencies ***"
  case "$DISTRO" in
    Debian|Ubuntu|Tuxedo)
      apt-get $YesOpt install \
        libjson-c4 \
        libsqlite3-0 \
	libarchive13
      ;;
    RedHatEnterprise*|CentOS|Fedora)
      yum $YesOpt install \
        json-c \
        sqlite-libs \
	libarchive
      ;;
  esac
fi
