# SPDX-FileCopyrightText: © 2011 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only
 

DIR = $(realpath .)

all:
	@echo "make nothing in $(DIR)"

install:
	@echo "make install nothing in $(DIR)"

uninstall:
	@echo "make uninstall nothing in $(DIR)"

clean:
	@echo "make uninstall nothing in $(DIR)"

.PHONY: all install uninstall clean
