# SPDX-FileCopyrightText: © 2011 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

all:
	@echo "nothing to do"

test:
	@echo "nothing to do"

coverage:
	@echo "nothing to do"

clean:
	@echo "nothing to do"

.PHONY: all test coverage clean
