<?php
$BINDIR="/usr/local/bin";
$LIBDIR="/usr/local/lib";
$LIBEXECDIR="/usr/local/lib/fossology";
$INCLUDEDIR="/usr/local/include";
$MAN1DIR="/usr/local/share/man/man1";
$AGENTDIR="/usr/local/lib/fossology/agents";
$SYSCONFDIR="/usr/local/etc";
$WEBDIR="/usr/local/share/fossology/www";
$PHPDIR="/usr/local/share/fossology/php";
$PROJECTSTATEDIR="/var/local/lib/fossology";
$PROJECT="fossology";
$DATADIR="/usr/local/share/fossology";
$VERSION="2.0";
$SVN_REV="4458M";
$FOSRCDIR="../../../src";
?>
