#!/bin/bash
# Copyright (C) 2013 Hewlett-Packard Development Company, L.P.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

# Script to generate the Unit Test Result together
cd /home/jenkins/jobs/Fossology_Unit_Tests/htmlreports/Unit_Test_Results/
echo "" > Unit_Tests_Results.html
ls *-Results* > /tmp/test.txt
while read fn; do
  name=`echo $fn|awk -F '-R' '{print $1}'`
  while read line; do
    if echo $line |grep -qE "A Unit testing framework for C"
    then
       echo "<b> $name Results" >> Unit_Tests_Results.html
    else
       echo $line >> Unit_Tests_Results.html
    fi
  done < $fn
done </tmp/test.txt
rm /tmp/test.txt

