#!/bin/bash
# SPDX-FileCopyrightText: © 2013 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

# Script to generate the Unit Test Result together
cd ../reports/unit
echo "" > Unit_Tests_Results.html
ls *-Results* > /tmp/test.txt
while read fn; do
  name=`echo $fn|awk -F '-R' '{print $1}'`
  while read line; do
    if echo $line |grep -qE "A Unit testing framework for C"
    then
       echo "<b> $name Results" >> Unit_Tests_Results.html
    else
       echo $line >> Unit_Tests_Results.html
    fi
  done < $fn
done </tmp/test.txt
rm /tmp/test.txt

