#include "nomos.h"
#include "_autodefs.h"
/*
 * ***************************************************************
 Copyright (C) 2006-2009 Hewlett-Packard Development Company, L.P.
 
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 version 2 as published by the Free Software Foundation.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along
 with this program; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 ***************************************************************
 *****
 * This source file was auto-generated Wed Apr 23 13:35:54 CST 2014
 *****
 * Changes to this file will NOT be kept; the file will be over-written
 * the next time the license-specifications (./STRINGS.in) change!
 *****
 * Words used for pre-check exclusions:
 */
#if	0
source
free
under
copyright
grant
software
distribut
licen
[iu][nst]
#endif
#define	M(x)	ltsr[x] = LTSR_SMASK;
extern int strGrep();
#ifdef	PROC_TRACE_SWITCH
extern struct globals gl;
#endif	/* PROC_TRACE_SWITCH */
#ifdef	LTSR_DEBUG
extern void showLTCache();
#endif	/* LTSR_DEBUG */
/* */
void preloadResults(char *filetext, char *ltsr)
{
#if	0
	int ret;	/* for possible debugging */
#endif
/* */
#ifdef	PROC_TRACE
#ifdef	PROC_TRACE_SWITCH
    if (gl.ptswitch)
#endif	/* PROC_TRACE_SWITCH */
	printf("== preloadResults(%p, %p, %d, %d)\n", filetext, ltsr);
#endif	/* PROC_TRACE */
/* */
	if (!strGrep("source", filetext, REG_ICASE)) {	/* match count 89 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"source\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_AFFERO2); M(_LT_AFFERO3); M(_LT_AGERE_EULA);
		M(_LT_ALGORITHMICS); M(_LT_APPLE_SAMPLE);
		M(_LT_APSLref1); M(_LT_ART_1); M(_LT_ART_2);
		M(_LT_ATT_SRC_1); M(_LT_ATT_SRC_2); M(_LT_BITTORRENT);
		M(_LT_BITTORRENTref); M(_LT_BITTORRENT_V11);
		M(_LT_BITTORRENT_V10); M(_LT_BSDref2);
		M(_LT_BSDref6); M(_LT_BSDSTYLEref3); M(_LT_BSD_1);
		M(_LT_BSD_10); M(_LT_BSD_11); M(_LT_BSD_CLAUSE_0);
		M(_LT_BSD_CLAUSE_1); M(_LT_CAMBRIDGE); M(_LT_CATHARON);
		M(_LT_CECILL_2); M(_LT_COMMERCIAL_2); M(_LT_COMPAQ_EULA);
		M(_LT_COMTROL); M(_LT_CUPS); M(_LT_CUPS_COMMERCIAL);
		M(_LT_DARPA_COUGAAR); M(_LT_DYADE); M(_LT_ECL);
		M(_LT_FRAMEWORX); M(_LT_FREE_12); M(_LT_FREE_24);
		M(_LT_FREE_28); M(_LT_FREE_29); M(_LT_FREE_30);
		M(_LT_FREE_36); M(_LT_FREE_38); M(_LT_FREE_41);
		M(_LT_FREE_48); M(_LT_FREE_57); M(_LT_FREE_60);
		M(_LT_FREE_61); M(_LT_FREE_77); M(_LT_FREE_79);
		M(_LT_FREETYPE); M(_LT_GOOGLE_2); M(_LT_RPSL_COMPATIBLE);
		M(_LT_FREEBSD_DOC); M(_LT_GS); M(_LT_IBM_PIBS);
		M(_LT_INNERNET); M(_LT_INTEL); M(_LT_IOSOFT_SRCONLY);
		M(_LT_JABBER_2); M(_LT_LACHMAN_SECRET); M(_LT_MIBBLE);
		M(_LT_MSCORP_PL); M(_LT_MSCORP_RL); M(_LT_MSCORP_SSLref);
		M(_LT_ND_1); M(_LT_NOT_OPENSOURCE); M(_LT_OG_3);
		M(_LT_OSD); M(_LT_OPENSSLref2); M(_LT_CNRI_PYTHON);
		M(_LT_CNRI_PYTHON_GPL); M(_LT_REAL_RCSLref);
		M(_LT_REAL_RPSLref); M(_LT_RECIP15);
		M(_LT_SGI_PROPRIETARY); M(_LT_SNIA_PL);
		M(_LT_SPIKESOURCE); M(_LT_SUN_SCSLref);
		M(_LT_SUN_SISSLref1); M(_LT_SUN_3); M(_LT_SUN_6);
		M(_LT_TEX_EXCEPT); M(_LT_USC); M(_LT_USC_NC);
		M(_LT_UUTAH); M(_LT_VIXIE); M(_LT_W3C_4); M(_LT_ZZGEN_15);
		M(_LT_ZZGEN_39); M(_LT_Oracle_Berkeley_DB);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"source\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("free", filetext, REG_ICASE)) {	/* match count 119 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"free\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_ADOBE_7); M(_LT_ADOBE_SRC); M(_LT_AFFERO1);
		M(_LT_AFFERO_V3); M(_LT_AFL); M(_LT_AFLref2);
		M(_LT_ARTref2); M(_LT_ASLref3); M(_LT_ASL);
		M(_LT_ASL20); M(_LT_ATT_SRC_2); M(_LT_BOOST_LAMBDA);
		M(_LT_BSDSTYLEref3); M(_LT_FREE_BSD); M(_LT_CC_GPL);
		M(_LT_CECILL_1); M(_LT_CECILL_2); M(_LT_CECILL_DUALref);
		M(_LT_CECILL_ref); M(_LT_COMPUSERVE);
		M(_LT_CPL_2); M(_LT_DARPA); M(_LT_DARPA_COUGAAR);
		M(_LT_DEB_CONTRACTref); M(_LT_EDINBURGH_1);
		M(_LT_EPINIONS); M(_LT_EPSON_EULA); M(_LT_FRAME);
		M(_LT_FREE_1); M(_LT_FREE_12); M(_LT_FREE_21);
		M(_LT_FREE_24); M(_LT_FREE_25); M(_LT_FREE_27);
		M(_LT_FREE_31); M(_LT_FREE_33); M(_LT_FREE_34);
		M(_LT_FREE_35); M(_LT_FREE_36); M(_LT_FREE_37);
		M(_LT_FREE_39); M(_LT_FREE_42); M(_LT_FREE_45);
		M(_LT_FREE_46); M(_LT_FREE_47); M(_LT_FREE_49);
		M(_LT_FREE_50); M(_LT_FREE_52); M(_LT_FREE_53);
		M(_LT_FREE_54); M(_LT_FREE_55); M(_LT_FREE_59);
		M(_LT_FREE_60); M(_LT_FREE_62); M(_LT_FREE_67);
		M(_LT_FREE_71); M(_LT_FREE_72); M(_LT_FREE_73);
		M(_LT_FREE_74); M(_LT_FREE_75); M(_LT_FREE_79);
		M(_LT_FREE_85); M(_LT_FREEART_V10); M(_LT_FREE_SW);
		M(_LT_FREETYPEref); M(_LT_FSFref1); M(_LT_FSFref2);
		M(_LT_GFDL); M(_LT_GOOGLE_2); M(_LT_GPL_EXCEPT_BISON_1);
		M(_LT_GPL_FONT1); M(_LT_GPL_FSF); M(_LT_GPLref3);
		M(_LT_GPLref19); M(_LT_IMAGEMAGICK);
		M(_LT_INDEMN_12); M(_LT_INTEL_2); M(_LT_LATEXref4);
		M(_LT_LDP); M(_LT_LGPLref4); M(_LT_LGPLref11);
		M(_LT_LINUXDOC); M(_LT_MIT_1); M(_LT_MIT_10);
		M(_LT_MITEM); M(_LT_MPEG3); M(_LT_MSCORP_1);
		M(_LT_MSCORP_3); M(_LT_MSCORP_5); M(_LT_MULTICORP_1);
		M(_LT_MULTICORP_2); M(_LT_NOT_FREE); M(_LT_NPL_2);
		M(_LT_NVIDIA); M(_LT_OSF_1); M(_LT_PIRIFORM);
		M(_LT_UNLIN); M(_LT_PUBDOM_USE); M(_LT_REAL_RCSL);
		M(_LT_RIVERBANK); M(_LT_RUBYref5); M(_LT_SUN_PRO);
		M(_LT_SUN_3); M(_LT_SUN_4); M(_LT_SUN_GRAPHICS);
		M(_LT_UCWARE_EULA_1); M(_LT_UNICODE_2); M(_LT_UNICODE_3);
		M(_LT_VIXIE); M(_LT_X11_1); M(_LT_ZEUS); M(_LT_ZZGEN_17);
		M(_LT_ZZGEN_24); M(_LT_ZZGEN_41); M(_LT_SEE_OUTPUT_1);
		M(_LT_XFREE86); M(_LT_XFREE86_V10); M(_LT_XFREE86_V11);
		M(_LT_FTL);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"free\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("under", filetext, REG_ICASE)) {	/* match count 189 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"under\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_OPEN_FONT_V10_1); M(_LT_OPEN_FONT_V11_1);
		M(_LT_ADOBE_SUB); M(_LT_AFFEROref1); M(_LT_AFFEROref2);
		M(_LT_AFL); M(_LT_AFLref1); M(_LT_ALADDIN_RESTRICT);
		M(_LT_APACHEref3); M(_LT_APACHESTYLEref); M(_LT_APPLE_3);
		M(_LT_APSLref2); M(_LT_ARTIFEX); M(_LT_ARTref3);
		M(_LT_ARTref4); M(_LT_ASLref3); M(_LT_ASL20ref);
		M(_LT_ASL20ref_2); M(_LT_ATT_1); M(_LT_BAEKMUK_2);
		M(_LT_BEA_2); M(_LT_BITSTREAM_2); M(_LT_BOGUSTMPL);
		M(_LT_BSDref2); M(_LT_BSDref3); M(_LT_BSDref5);
		M(_LT_BSDSTYLEref1); M(_LT_CATHARON); M(_LT_CCA_ref);
		M(_LT_CCA_SA); M(_LT_CCA_SAref); M(_LT_CCA_ND_ref);
		M(_LT_CCA_BY_V30); M(_LT_CDDL); M(_LT_CECILL_2_ref);
		M(_LT_CECILL_DUALref); M(_LT_CECILL_ref);
		M(_LT_CECILL_ref2); M(_LT_CECILL_B_ref); M(_LT_COMPAQ_1);
		M(_LT_COPYLEFT_2); M(_LT_CPAL_V1_ref); M(_LT_CPOL);
		M(_LT_CPL_1); M(_LT_CUPS); M(_LT_CUPS_COMMERCIAL);
		M(_LT_DARPA); M(_LT_DARPA_COUGAAR); M(_LT_DEC_2);
		M(_LT_DUAL_LICENSE_1); M(_LT_DUAL_LICENSE_2);
		M(_LT_DUAL_LICENSE_3); M(_LT_DUAL_LICENSE_3_EXHIBIT);
		M(_LT_DUAL_LICENSE_4); M(_LT_DUAL_LICENSE_6);
		M(_LT_DUAL_LICENSE_7); M(_LT_DUAL_LICENSE_8);
		M(_LT_DUAL_LICENSE_10); M(_LT_DUAL_LICENSE_11);
		M(_LT_ECL1); M(_LT_ECL2); M(_LT_ECLIPSEref);
		M(_LT_EIFFEL_1); M(_LT_FEDORA_CLA); M(_LT_FREE_20);
		M(_LT_FREE_36); M(_LT_FREETYPEref); M(_LT_FSF_5);
		M(_LT_GARMIN_EULA); M(_LT_GEN_PROPRIETARY_2);
		M(_LT_GFDLref1); M(_LT_GNU_PROJECTS); M(_LT_GOOGLE_2);
		M(_LT_GPL_ALT); M(_LT_GPL_EXCEPT_BISON_2);
		M(_LT_GPL_FONT1); M(_LT_GPL_FSF); M(_LT_GPL_META_DEBIAN);
		M(_LT_GPLpatt1); M(_LT_GPLref1); M(_LT_GPLref6);
		M(_LT_GPLref8); M(_LT_GPLref12); M(_LT_GPL_ref);
		M(_LT_GPL_V2); M(_LT_GPL_V2_ref1); M(_LT_GPL_V2_ref);
		M(_LT_GPL_V3_ref); M(_LT_GPL3ref); M(_LT_GPL3ref2);
		M(_LT_FORMER_GNU); M(_LT_GS_GNU1); M(_LT_HAUPPAUGE);
		M(_LT_HP_EULA1); M(_LT_IBM_2); M(_LT_IBM_COURIER);
		M(_LT_IBM_PLref1); M(_LT_IBM_PIBS); M(_LT_INTEL_2);
		M(_LT_INTEL_4); M(_LT_INTEL_EULA); M(_LT_IPA_EULA);
		M(_LT_LATEXref3); M(_LT_LATEXref5); M(_LT_LATEX_PREAMBLE);
		M(_LT_LATEXPL_2); M(_LT_LATEXPLref1); M(_LT_LATEXPLref2);
		M(_LT_LATEXPLref3); M(_LT_LDPref1); M(_LT_LDPref2);
		M(_LT_LGPL_ALT); M(_LT_LGPLref1); M(_LT_LGPLref2);
		M(_LT_LGPLref4); M(_LT_LGPLref5); M(_LT_LGPLref10);
		M(_LT_LGPLrefFSF); M(_LT_LGPL3ref); M(_LT_MANPAGE);
		M(_LT_MIT_10); M(_LT_MITref1); M(_LT_MPL_OR_MITX);
		M(_LT_MSCORP_EULA_2); M(_LT_MSCORP_PL);
		M(_LT_MSCORP_PLref2); M(_LT_MSCORP_SSLref);
		M(_LT_MULTICORP_1); M(_LT_MULTICORP_2);
		M(_LT_NOKIA); M(_LT_NOVELL); M(_LT_OMRON1);
		M(_LT_OSD); M(_LT_OPENSSLref1); M(_LT_OSLref1);
		M(_LT_OSLref2); M(_LT_PERLref1); M(_LT_PHP_ref);
		M(_LT_PNG_ZLIBref1); M(_LT_PRINCETON); M(_LT_PUBDOM_ODC);
		M(_LT_PYTHON_4); M(_LT_QPLref); M(_LT_RECIP_1);
		M(_LT_REDLAND); M(_LT_RH_1); M(_LT_RUBY);
		M(_LT_RUBYref1); M(_LT_RUBYref2); M(_LT_RUBYref3);
		M(_LT_RUBYref4); M(_LT_RUBYref5); M(_LT_SAME_LICENSE_1);
		M(_LT_SGI_GLX); M(_LT_SNIA_PL); M(_LT_SPIKESOURCE);
		M(_LT_SUN_BCLAref); M(_LT_SUN_ENTITLE);
		M(_LT_SUN_PLref); M(_LT_SUN_PROPRIETARY);
		M(_LT_UMONASH); M(_LT_USGOVT_RIGHTS2); M(_LT_UW4);
		M(_LT_WINTERTREE); M(_LT_WTFPLref); M(_LT_X11_4);
		M(_LT_X11_STYLE); M(_LT_ZZGEN_21); M(_LT_ZZGEN_24);
		M(_LT_SEE_COPYING_1); M(_LT_SEE_COPYING_2);
		M(_LT_SEE_COPYING_6); M(_LT_SEE_OTHER_1);
		M(_LT_SEE_OTHER_2); M(_LT_SEE_OTHER_3);
		M(_LT_SEE_OTHER_7); M(_LT_SEE_LICENSE_1);
		M(_LT_SEE_LICENSE_2); M(_LT_SEE_LICENSE_6);
		M(_LT_SEE_OUTPUT_1); M(_LT_SEE_README_1);
		M(_LT_SEE_README_2); M(_LT_SEE_README_6); M(_LT_XFREE86);
		M(_LT_MX4J_V10); M(_LT_MX4J); M(_LT_LIBGCJ); M(_LT_FTL);
		M(_LT_ClearSilver);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"under\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("copyright", filetext, REG_ICASE)) {	/* match count 111 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"copyright\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_ADOBE_2); M(_LT_ADOBE_AFM); M(_LT_ADOBE_SRC);
		M(_LT_ADOBE_SUB); M(_LT_ALGORITHMICS); M(_LT_APACHE_2);
		M(_LT_ASLref3); M(_LT_ASL); M(_LT_BIZNET);
		M(_LT_BSDSTYLEref2); M(_LT_BSD_4); M(_LT_BSD_10);
		M(_LT_BSD_CLAUSE_1); M(_LT_BSD_CLAUSE_2);
		M(_LT_UC); M(_LT_CMU_3); M(_LT_CPL_2);
		M(_LT_CYPRESS); M(_LT_FREE_2); M(_LT_FREE_3);
		M(_LT_FREE_4); M(_LT_FREE_8); M(_LT_FREE_9);
		M(_LT_FREE_10); M(_LT_FREE_11); M(_LT_FREE_13);
		M(_LT_FREE_15); M(_LT_FREE_17); M(_LT_FREE_18);
		M(_LT_FREE_25); M(_LT_FREE_26); M(_LT_FREE_27);
		M(_LT_FREE_32); M(_LT_FREE_33); M(_LT_FREE_34);
		M(_LT_FREE_38); M(_LT_FREE_43); M(_LT_FREE_46);
		M(_LT_FREE_47); M(_LT_FREE_56); M(_LT_FREE_57);
		M(_LT_FREE_59); M(_LT_FREE_64); M(_LT_FREE_65);
		M(_LT_FREE_68); M(_LT_FREE_69); M(_LT_FREE_70);
		M(_LT_FREE_84); M(_LT_GARMIN_EULA); M(_LT_GEN_IP_3);
		M(_LT_GEN_PROPRIETARY_1); M(_LT_GLIDE_GPL); M(_LT_GPL_1);
		M(_LT_GPL_2); M(_LT_GS); M(_LT_HP_1); M(_LT_IBM_2);
		M(_LT_IBM_PIBS); M(_LT_IETF_2); M(_LT_IETF_4);
		M(_LT_INTEL_RESTRICT); M(_LT_JPEG_1); M(_LT_KDAB_1);
		M(_LT_KNUTH_2); M(_LT_LATEXref1); M(_LT_LATEXPL_3);
		M(_LT_LEGATO_1); M(_LT_LINUX_HOWTO); M(_LT_MIT_4);
		M(_LT_MIT_6); M(_LT_MIT_7); M(_LT_MITRE_2); M(_LT_MOT_2);
		M(_LT_MSCORP_4); M(_LT_NOKIA); M(_LT_NONCOMMERCIAL_1);
		M(_LT_NTP); M(_LT_NVIDIA); M(_LT_PNG_ZLIBref3);
		M(_LT_PUBDOMNOTcpyrt); M(_LT_PYTHON_2);
		M(_LT_PYTHON_3); M(_LT_RUBY); M(_LT_SGI_1);
		M(_LT_SGI_GLX); M(_LT_SPI); M(_LT_SRA); M(_LT_SSLEAY);
		M(_LT_SUN_JAVA); M(_LT_SUN_SCA); M(_LT_SUNrestrict);
		M(_LT_SUN_6); M(_LT_UBC); M(_LT_UCAR_2); M(_LT_USL_EUR);
		M(_LT_UUTAH); M(_LT_W3C_6); M(_LT_W3Cref3); M(_LT_ZEUS);
		M(_LT_ZZGEN_32); M(_LT_ZZGEN_33); M(_LT_SEE_COPYING_7);
		M(_LT_SEE_COPYING_15); M(_LT_SEE_OTHER_9);
		M(_LT_SEE_OTHER_10); M(_LT_SEE_OTHER_11);
		M(_LT_SEE_OTHER_12); M(_LT_SEE_LICENSE_7);
		M(_LT_SEE_LICENSE_9); M(_LT_SEE_README_7);
		M(_LT_Oracle_Berkeley_DB);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"copyright\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("grant", filetext, REG_ICASE)) {	/* match count 183 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"grant\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_ADAPTEC_OBJ); M(_LT_ADOBE_1); M(_LT_ADOBE_2);
		M(_LT_ADOBE_7); M(_LT_ADOBE_DATA); M(_LT_ADOBE_SRC);
		M(_LT_ADOBE_SUB); M(_LT_AFL); M(_LT_AGE); M(_LT_AMD);
		M(_LT_APACHE_1); M(_LT_APPLE_2); M(_LT_APTANA);
		M(_LT_ASCENDER_EULA); M(_LT_ASL); M(_LT_ASL20);
		M(_LT_BAEKMUK_2); M(_LT_BANCTEC); M(_LT_BEA_2);
		M(_LT_BITSTREAM_2); M(_LT_BIZNET); M(_LT_BOOST_LAMBDA);
		M(_LT_BSD_2); M(_LT_BSD_4); M(_LT_BSD_6); M(_LT_BSD_7);
		M(_LT_BSD_8); M(_LT_BSD_13); M(_LT_BSD_NONC);
		M(_LT_BSD_CLAUSE_CLEAR); M(_LT_CADENCE); M(_LT_CCPL);
		M(_LT_CECILL_1); M(_LT_CECILL_2); M(_LT_COMPAQ_EULA);
		M(_LT_COMPUSERVE); M(_LT_CMU_1); M(_LT_CMU_2);
		M(_LT_CMU_6); M(_LT_CPL_2); M(_LT_CYPRESS);
		M(_LT_EDINBURGH_1); M(_LT_EDS_2); M(_LT_EIFFEL);
		M(_LT_EPSON_EULA); M(_LT_FEDORA); M(_LT_FREE_1);
		M(_LT_FREE_2); M(_LT_FREE_3); M(_LT_FREE_4);
		M(_LT_FREE_5); M(_LT_FREE_6); M(_LT_FREE_7);
		M(_LT_FREE_8); M(_LT_FREE_9); M(_LT_FREE_10);
		M(_LT_FREE_11); M(_LT_FREE_12); M(_LT_FREE_13);
		M(_LT_FREE_15); M(_LT_FREE_17); M(_LT_FREE_18);
		M(_LT_FREE_19); M(_LT_FREE_20); M(_LT_FREE_22);
		M(_LT_FREE_23); M(_LT_FREE_26); M(_LT_FREE_34);
		M(_LT_FREE_38); M(_LT_FREE_43); M(_LT_FREE_48);
		M(_LT_FREE_56); M(_LT_FREE_58); M(_LT_FREE_63);
		M(_LT_FREE_64); M(_LT_FREE_65); M(_LT_FREE_66);
		M(_LT_FREE_67); M(_LT_FREE_69); M(_LT_FREE_78);
		M(_LT_FREE_79); M(_LT_FREE_85); M(_LT_FREEART_V13);
		M(_LT_FREEPL); M(_LT_FREE_SW); M(_LT_FSF_2);
		M(_LT_GFDLref1); M(_LT_GNU_3); M(_LT_GPLref6);
		M(_LT_GS_GNU1); M(_LT_HP_IBM_1); M(_LT_HP_IBM_2);
		M(_LT_HP_4); M(_LT_HP_7); M(_LT_HP_DEC);
		M(_LT_HP_PROPRIETARY_3); M(_LT_IBM_1); M(_LT_IBM_2);
		M(_LT_IBM_3); M(_LT_IBM_COURIER); M(_LT_IBM_RECIP);
		M(_LT_IMAGEMAGICK); M(_LT_INNERNET); M(_LT_INTEL_2);
		M(_LT_INTEL_5); M(_LT_IOS); M(_LT_IPA_EULA);
		M(_LT_IRONDOC); M(_LT_JAVA_WSDL4J); M(_LT_JAVA_WSDL_ENUM);
		M(_LT_JAVA_WSDL_POLICY); M(_LT_JAVA_WSDL_SCHEMA);
		M(_LT_JPEG_2); M(_LT_KDAB_2); M(_LT_KEYSPAN);
		M(_LT_KNUTH_2); M(_LT_LATEXref2); M(_LT_MACROV_IA);
		M(_LT_MANPAGE); M(_LT_MIT_1); M(_LT_MIT_3); M(_LT_MIT_4);
		M(_LT_MIT_5); M(_LT_MIT_6); M(_LT_MIT_9); M(_LT_MIT_11);
		M(_LT_MOT_1); M(_LT_MOT_2); M(_LT_MSCORP_3);
		M(_LT_MSCORP_4); M(_LT_MULTICORP_2); M(_LT_NASA);
		M(_LT_ND_2); M(_LT_NESSUS); M(_LT_NONPROFIT_1);
		M(_LT_NPL_2); M(_LT_NTP); M(_LT_NVIDIA);
		M(_LT_NVIDIA_EULA); M(_LT_OMRON2); M(_LT_ORACLE_DEVEL);
		M(_LT_ORACLE_PROTO); M(_LT_OREILLY_1); M(_LT_OSF_1);
		M(_LT_OSF_2); M(_LT_OSL_BAD); M(_LT_OPENSSLref2);
		M(_LT_PHP); M(_LT_PNG_ZLIB_2); M(_LT_PUBDOM_PDD);
		M(_LT_PYTHON_2); M(_LT_RECIP_1); M(_LT_RH_FEDORA);
		M(_LT_RH_REDHAT); M(_LT_RIVERBANK); M(_LT_RSA_2);
		M(_LT_RSA_4); M(_LT_RSA_5); M(_LT_SGI_1); M(_LT_SGI_GLX);
		M(_LT_SLEEPYCAT_NC); M(_LT_SRA); M(_LT_SUN_PRO);
		M(_LT_SUN_6); M(_LT_SUN_GRAPHICS); M(_LT_SUN_NC);
		M(_LT_TEKTRONIX); M(_LT_TROLLTECH); M(_LT_UCHICAGO);
		M(_LT_UCWARE_EULA_1); M(_LT_USC); M(_LT_UMICHIGAN_2);
		M(_LT_UNICODE_2); M(_LT_UNICODE_3); M(_LT_USGOVT_2);
		M(_LT_USL_EUR); M(_LT_UW3); M(_LT_VMWARE); M(_LT_W3C_4);
		M(_LT_W3C_6); M(_LT_X11_2); M(_LT_X11_3); M(_LT_ZZGEN_34);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"grant\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("software", filetext, REG_ICASE)) {	/* match count 216 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"software\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_Imlib2); M(_LT_ACAA_RIGHTS); M(_LT_ADAPTEC_GPL);
		M(_LT_ANTLR); M(_LT_ADAPTEC_OBJ); M(_LT_ADOBE_2);
		M(_LT_ADOBE_4); M(_LT_ADOBE_6); M(_LT_ADOBE_7);
		M(_LT_ADOBE_SUB); M(_LT_AFFERO1); M(_LT_AFFERO_V3);
		M(_LT_AGERE_EULA); M(_LT_AMD_EULA); M(_LT_APPLE_1);
		M(_LT_APPLE_3); M(_LT_APPLE_4); M(_LT_ARPHIC);
		M(_LT_ARJ); M(_LT_ASCENDER_EULA); M(_LT_ASL11ref);
		M(_LT_ASLref1); M(_LT_ASLref3); M(_LT_ATMEL);
		M(_LT_ATT_2); M(_LT_ATT_NONCOMMERC2); M(_LT_AVM_1);
		M(_LT_AVM_2); M(_LT_BANCTEC); M(_LT_BH_FONT);
		M(_LT_BITSTREAM_1); M(_LT_BITTORRENT); M(_LT_BIZNET);
		M(_LT_BOOST_1); M(_LT_BOOST_LAMBDA); M(_LT_BOOSTref1);
		M(_LT_BROADCOM_EULA); M(_LT_BSDref7); M(_LT_BSD_2);
		M(_LT_BSD_5); M(_LT_BSD_8); M(_LT_BSD_9);
		M(_LT_BSD_CLAUSE_3); M(_LT_BSD_CLAUSE_4);
		M(_LT_XML_DB_V10); M(_LT_FREE_BSD); M(_LT_CADENCE);
		M(_LT_CECILL_1); M(_LT_CECILL_2); M(_LT_CECILL_DUALref);
		M(_LT_CECILL_ref); M(_LT_CECILL_ref1);
		M(_LT_CISCO); M(_LT_CMU_1); M(_LT_CMU_2);
		M(_LT_CMU_4); M(_LT_CMU_6); M(_LT_COPYLEFT_2);
		M(_LT_CPL_1); M(_LT_CUPS); M(_LT_CUPS_COMMERCIAL);
		M(_LT_CYLINK_ISC_1); M(_LT_DARPA); M(_LT_DARPA_COUGAAR);
		M(_LT_DEB_CONTRACTref); M(_LT_DSCT); M(_LT_ECL);
		M(_LT_EDINBURGH_2); M(_LT_EDS_1); M(_LT_EDS_2);
		M(_LT_EU); M(_LT_EXPORTS_USA); M(_LT_FREE_1);
		M(_LT_FREE_5); M(_LT_FREE_6); M(_LT_FREE_9);
		M(_LT_FREE_22); M(_LT_FREE_23); M(_LT_FREE_26);
		M(_LT_FREE_27); M(_LT_FREE_31); M(_LT_FREE_36);
		M(_LT_FREE_37); M(_LT_FREE_39); M(_LT_FREE_40);
		M(_LT_FREE_41); M(_LT_FREE_42); M(_LT_FREE_44);
		M(_LT_FREE_50); M(_LT_FREE_54); M(_LT_FREE_55);
		M(_LT_FREE_71); M(_LT_FREE_72); M(_LT_FREE_74);
		M(_LT_FREE_85); M(_LT_FSFref1); M(_LT_GARMIN_EULA);
		M(_LT_GEN_PROPRIETARY_2); M(_LT_GFDL); M(_LT_GOOGLE_2);
		M(_LT_GPL_EXCEPT_BISON_1); M(_LT_GPL_FONT1);
		M(_LT_GPL_FSF); M(_LT_GPLref11); M(_LT_GPLref19);
		M(_LT_HP_EULA1); M(_LT_HP_6); M(_LT_HP_DEC);
		M(_LT_HP_PROPRIETARY_1); M(_LT_HP_PROPRIETARY_2);
		M(_LT_HP_PROPRIETARY_3); M(_LT_IBM_1); M(_LT_ID_EULA);
		M(_LT_IMAGEMAGICK); M(_LT_INFOSEEK); M(_LT_INTEL_1);
		M(_LT_INTEL_3); M(_LT_INTEL_6); M(_LT_INTEL_7);
		M(_LT_INTEL_FW); M(_LT_IRONDOC); M(_LT_JABBER_1);
		M(_LT_JPEG_2); M(_LT_KDAB_1); M(_LT_KDAB_2);
		M(_LT_KNUTH_2); M(_LT_LARABIE_EULA); M(_LT_LATEX);
		M(_LT_LGPLref5); M(_LT_LGPLref11); M(_LT_MACROV_IA);
		M(_LT_METRO); M(_LT_METRO_NONFREE); M(_LT_MIBBLE);
		M(_LT_MIT_0); M(_LT_MIT_3); M(_LT_MIT_5);
		M(_LT_MIT_6); M(_LT_MIT_8); M(_LT_MIT_9); M(_LT_MPEG3);
		M(_LT_MPL_1); M(_LT_MPL_OR_MITX); M(_LT_MSCORP_3);
		M(_LT_MSCORP_EULA_3); M(_LT_MSCORP_EULA_4);
		M(_LT_MSCORP_LIMITED); M(_LT_MSCORP_PL);
		M(_LT_MSCORP_PLref1); M(_LT_MSCORP_REFLIC);
		M(_LT_MSCORP_RL); M(_LT_MSCORP_RLref); M(_LT_MULTICS);
		M(_LT_NASA); M(_LT_NCIPHER); M(_LT_NPL_2); M(_LT_NTP);
		M(_LT_NVIDIA_EULA); M(_LT_NVIDIA_EULA_2); M(_LT_OG_1);
		M(_LT_OG_2); M(_LT_OMRON2); M(_LT_OPENLDAP_1);
		M(_LT_OPENMKT); M(_LT_OSF_1); M(_LT_OSLref1);
		M(_LT_PARADIGM); M(_LT_PERL_3); M(_LT_PHP);
		M(_LT_PIRIFORM); M(_LT_PIXWARE_EULA); M(_LT_PNG_ZLIB_1);
		M(_LT_QUALCOMM); M(_LT_QUARTERDECK); M(_LT_QPL);
		M(_LT_QUEST_EULA); M(_LT_RUBY); M(_LT_RUBYref5);
		M(_LT_SGI_1); M(_LT_SGI_GLX); M(_LT_SLEEPYCAT_NC);
		M(_LT_SUN_ENTITLE); M(_LT_SUN_JAVA); M(_LT_SUN_3);
		M(_LT_SUN_4); M(_LT_SUN_6); M(_LT_SUN_GRAPHICS);
		M(_LT_SUN_NC); M(_LT_UCAR_1); M(_LT_UCWARE_EULA_1);
		M(_LT_USC); M(_LT_UMICHIGAN_1); M(_LT_UMICHIGAN_2);
		M(_LT_USGOVT_RIGHTS1); M(_LT_USGOVT_RIGHTS2);
		M(_LT_USC_NC); M(_LT_USL_EUR); M(_LT_UW3); M(_LT_W3C_2);
		M(_LT_W3C_3); M(_LT_W3C_7); M(_LT_W3Cref1);
		M(_LT_W3Cref2); M(_LT_W3Cref3); M(_LT_W3Cref4);
		M(_LT_WINTERTREE); M(_LT_WU_FTPDref); M(_LT_X11_3);
		M(_LT_XEROX_1); M(_LT_XIMIAN); M(_LT_XOPEN_2);
		M(_LT_YAHOO_1); M(_LT_ZVENO); M(_LT_SEE_OTHER_10);
		M(_LT_SEE_OUTPUT_1); M(_LT_Oracle_Berkeley_DB);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"software\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("distribut", filetext, REG_ICASE)) {	/* match count 383 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"distribut\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_ACDL); M(_LT_ADAPTEC_GPL); M(_LT_ADOBE_2);
		M(_LT_ADOBE_3); M(_LT_ADOBE_5); M(_LT_ADOBE_6);
		M(_LT_ADOBE_AFM); M(_LT_ADOBE_DATA); M(_LT_ADOBE_OTHER);
		M(_LT_ADOBE_SUB); M(_LT_AFFEROref1); M(_LT_AGE);
		M(_LT_AGERE_EULA); M(_LT_AGFA); M(_LT_ALGORITHMICS);
		M(_LT_ALADDIN_RESTRICT); M(_LT_AMD); M(_LT_AMD_EULA);
		M(_LT_APACHE_1); M(_LT_APACHE_2); M(_LT_APACHEref1);
		M(_LT_ARJ); M(_LT_ARTIFEX); M(_LT_ARTref3);
		M(_LT_ARTref4); M(_LT_ART_V2); M(_LT_ASCENDER_EULA);
		M(_LT_ATMEL); M(_LT_ATT_2); M(_LT_ATT_SRC_2);
		M(_LT_AVM_3); M(_LT_BAEKMUK_1); M(_LT_BAEKMUK_2);
		M(_LT_BANCTEC); M(_LT_BELLCORE); M(_LT_BISON);
		M(_LT_BITSTREAM_2); M(_LT_BIZNET); M(_LT_BOGUSTMPL);
		M(_LT_BOOST_2); M(_LT_BOOST_LAMBDA); M(_LT_BSDref2);
		M(_LT_BSDref3); M(_LT_BSDref4); M(_LT_BSDref6);
		M(_LT_BSDSTYLEref3); M(_LT_BSD_1); M(_LT_BSD_2);
		M(_LT_BSD_3); M(_LT_BSD_4); M(_LT_BSD_7);
		M(_LT_BSD_8); M(_LT_BSD_10); M(_LT_BSD_11);
		M(_LT_BSD_13); M(_LT_BSD_NONC); M(_LT_BSD_CLAUSE_0);
		M(_LT_BSD_CLAUSE_1); M(_LT_BSD_CLAUSE_2); M(_LT_CADENCE);
		M(_LT_CATHARON); M(_LT_CCA_2); M(_LT_CCA_SA);
		M(_LT_CDDL10ref); M(_LT_CDDLref); M(_LT_CECILL_1);
		M(_LT_CECILL_2); M(_LT_CECILL_DUALref); M(_LT_CECILL_ref);
		M(_LT_COLUMBIA); M(_LT_COMMERCIAL_1); M(_LT_COMMERCIAL_2);
		M(_LT_COMPAQ_EULA); M(_LT_CMU_1); M(_LT_CMU_2);
		M(_LT_CMU_4); M(_LT_COMTROL); M(_LT_COPYLEFT_1);
		M(_LT_CPL_1); M(_LT_CUPS_COMMERCIAL); M(_LT_CYLINK_ISC_2);
		M(_LT_DARPA); M(_LT_DARPA_COUGAAR); M(_LT_DELAWARE);
		M(_LT_DOCBOOK); M(_LT_DPTC); M(_LT_DSCT); M(_LT_DSL);
		M(_LT_DUAL_LICENSE_8); M(_LT_DUAL_LICENSE_11); M(_LT_EBT);
		M(_LT_EDINBURGH_1); M(_LT_EDINBURGH_2); M(_LT_EIFFEL);
		M(_LT_EPINIONS); M(_LT_EPSON_PL); M(_LT_EU); M(_LT_FRAME);
		M(_LT_FRAMEWORX); M(_LT_FREE_1); M(_LT_FREE_2);
		M(_LT_FREE_3); M(_LT_FREE_4); M(_LT_FREE_5);
		M(_LT_FREE_6); M(_LT_FREE_7); M(_LT_FREE_8);
		M(_LT_FREE_9); M(_LT_FREE_10); M(_LT_FREE_12);
		M(_LT_FREE_13); M(_LT_FREE_15); M(_LT_FREE_16);
		M(_LT_FREE_17); M(_LT_FREE_18); M(_LT_FREE_19);
		M(_LT_FREE_20); M(_LT_FREE_21); M(_LT_FREE_22);
		M(_LT_FREE_23); M(_LT_FREE_24); M(_LT_FREE_25);
		M(_LT_FREE_26); M(_LT_FREE_27); M(_LT_FREE_28);
		M(_LT_FREE_29); M(_LT_FREE_30); M(_LT_FREE_31);
		M(_LT_FREE_32); M(_LT_FREE_33); M(_LT_FREE_34);
		M(_LT_FREE_35); M(_LT_FREE_36); M(_LT_FREE_37);
		M(_LT_FREE_38); M(_LT_FREE_39); M(_LT_FREE_40);
		M(_LT_FREE_41); M(_LT_FREE_42); M(_LT_FREE_43);
		M(_LT_FREE_44); M(_LT_FREE_45); M(_LT_FREE_46);
		M(_LT_FREE_47); M(_LT_FREE_48); M(_LT_FREE_49);
		M(_LT_FREE_50); M(_LT_FREE_51); M(_LT_FREE_52);
		M(_LT_FREE_53); M(_LT_FREE_54); M(_LT_FREE_55);
		M(_LT_FREE_56); M(_LT_FREE_57); M(_LT_FREE_58);
		M(_LT_FREE_59); M(_LT_FREE_60); M(_LT_FREE_61);
		M(_LT_FREE_62); M(_LT_FREE_63); M(_LT_FREE_64);
		M(_LT_FREE_65); M(_LT_FREE_66); M(_LT_FREE_67);
		M(_LT_FREE_71); M(_LT_FREE_77); M(_LT_FREE_81);
		M(_LT_FREE_84); M(_LT_FREE_85); M(_LT_FREEART_V10);
		M(_LT_FREE_SW); M(_LT_FREETYPE); M(_LT_FREETYPEref);
		M(_LT_FSF_1); M(_LT_FSF_2); M(_LT_FSF_3); M(_LT_FSF_4);
		M(_LT_FSF_5); M(_LT_FSFref2); M(_LT_GFDLref1);
		M(_LT_GNU_1); M(_LT_GNU_3); M(_LT_GNU_PROJECTS);
		M(_LT_GPL_EXCEPT_1); M(_LT_GPL_EXCEPT_2);
		M(_LT_GPL_EXCEPT_BISON_2); M(_LT_GPL_FONT2);
		M(_LT_GPL_FSF); M(_LT_GPLref2); M(_LT_GPLref3);
		M(_LT_GPLref5); M(_LT_GPLref6); M(_LT_GPLref10);
		M(_LT_GPLref11); M(_LT_GPLref20); M(_LT_GPL_2);
		M(_LT_FREEBSD_DOC); M(_LT_GS_GNU1); M(_LT_GS_GNU2);
		M(_LT_GS); M(_LT_HP_3); M(_LT_HP_4); M(_LT_HP_5);
		M(_LT_HP_7); M(_LT_HP_DEC); M(_LT_IBM_1); M(_LT_IBM_3);
		M(_LT_IBM_COURIER); M(_LT_IBM_RECIP); M(_LT_IEEE_DOC);
		M(_LT_INFOSEEK); M(_LT_INNERNET); M(_LT_INTEL_3);
		M(_LT_INTRANET_ONLY); M(_LT_IOSOFT_SRCONLY);
		M(_LT_JABBER_1); M(_LT_JAVA_WSDL_SCHEMA); M(_LT_JPEG_2);
		M(_LT_KEYSPAN); M(_LT_KNUTH_2); M(_LT_LACHMAN_SECRET);
		M(_LT_LARABIE_EULA); M(_LT_LATEXref3); M(_LT_LATEXref4);
		M(_LT_LATEX); M(_LT_LATEX_PREAMBLE); M(_LT_LATEXPL_1);
		M(_LT_LATEXPL_2); M(_LT_LATEXPL_3); M(_LT_LATEXPLref1);
		M(_LT_LATEXPLref2); M(_LT_LATEXPLref3); M(_LT_LDP);
		M(_LT_LDPref1); M(_LT_LEGATO_1); M(_LT_LGPLref1);
		M(_LT_LGPLref5); M(_LT_LGPL_1); M(_LT_LGPL_2);
		M(_LT_LINUXDOC); M(_LT_MANPAGE); M(_LT_MELLANOX);
		M(_LT_MIBBLE); M(_LT_MITDOC); M(_LT_MIT_2); M(_LT_MIT_3);
		M(_LT_MIT_4); M(_LT_MIT_5); M(_LT_MIT_6); M(_LT_MIT_8);
		M(_LT_MIT_9); M(_LT_MIT_10); M(_LT_MIT_11);
		M(_LT_MITEM); M(_LT_MITRE_1); M(_LT_MOT_2);
		M(_LT_MPEG3); M(_LT_MPL_2); M(_LT_MPL_OR_MITX);
		M(_LT_MSCORP_1); M(_LT_MSCORP_2); M(_LT_MSCORP_3);
		M(_LT_MSCORP_5); M(_LT_MSCORP_IP_1); M(_LT_MSCORP_PL);
		M(_LT_MSCORPref1); M(_LT_MSCORP_RL); M(_LT_MYSQL_EXCEPT);
		M(_LT_ND_1); M(_LT_ND_3); M(_LT_NONPROFIT_1);
		M(_LT_NOT_FREE); M(_LT_NOVELL); M(_LT_NPL_2);
		M(_LT_NTP); M(_LT_OG_1); M(_LT_OG_2); M(_LT_OMRON2);
		M(_LT_OPENLDAP_1); M(_LT_OPENMKT); M(_LT_OPENPUBL_1);
		M(_LT_OPENPUBL_2); M(_LT_OREILLY_2); M(_LT_OSF_1);
		M(_LT_OSF_2); M(_LT_OPENSSLref1); M(_LT_OPENSSLref2);
		M(_LT_OSLref1); M(_LT_PARADIGM); M(_LT_PERLref1);
		M(_LT_PERLref2); M(_LT_PERLref3); M(_LT_PERL_2);
		M(_LT_PERL_3); M(_LT_PNG_ZLIB_2); M(_LT_PNG_ZLIBref3);
		M(_LT_NOTPUBDOM_1); M(_LT_PUBDOM_USE); M(_LT_PUBLIC_USE);
		M(_LT_PYTHON_1); M(_LT_PYTHONref1); M(_LT_QUARTERDECK);
		M(_LT_RH_NONCOMMERCIAL); M(_LT_RH_PKGS); M(_LT_RSA_5);
		M(_LT_RUBYref2); M(_LT_RUBYref3); M(_LT_RUBYref4);
		M(_LT_RUBYref5); M(_LT_SGI_1); M(_LT_SGI_FREEW);
		M(_LT_SKYPE); M(_LT_SRA); M(_LT_SUN_SCSL_TSA);
		M(_LT_SUN_PRO); M(_LT_SUN_RPC); M(_LT_SUN_3);
		M(_LT_SUN_4); M(_LT_SUN_6); M(_LT_SUN_GRAPHICS);
		M(_LT_SUN_NC); M(_LT_UCAR_1); M(_LT_UCHICAGO); M(_LT_USC);
		M(_LT_UMICHIGAN_1); M(_LT_UMICHIGAN_2); M(_LT_UMONASH);
		M(_LT_UNICODE_1); M(_LT_UNICODE_2); M(_LT_USC_NC);
		M(_LT_USL_EUR); M(_LT_UW1); M(_LT_UW2); M(_LT_UW3);
		M(_LT_VIM_1); M(_LT_VIM_2); M(_LT_VIXIE); M(_LT_W3C_1);
		M(_LT_W3C_2); M(_LT_W3C_3); M(_LT_W3C_4); M(_LT_W3C_5);
		M(_LT_W3Cref2); M(_LT_WTFPL); M(_LT_WU_FTPD);
		M(_LT_X11_2); M(_LT_X11_3); M(_LT_X11_STYLE);
		M(_LT_XIMIAN); M(_LT_XOPEN_2); M(_LT_YAHOO_BINARY);
		M(_LT_ZZGEN_1); M(_LT_ZZGEN_2); M(_LT_ZZGEN_3);
		M(_LT_ZZGEN_4); M(_LT_ZZGEN_5); M(_LT_ZZGEN_6);
		M(_LT_ZZGEN_7); M(_LT_ZZGEN_8); M(_LT_ZZGEN_10);
		M(_LT_ZZGEN_11); M(_LT_ZZGEN_12); M(_LT_ZZGEN_13);
		M(_LT_ZZGEN_14); M(_LT_ZZGEN_15); M(_LT_ZZGEN_16);
		M(_LT_ZZGEN_17); M(_LT_ZZGEN_18); M(_LT_ZZGEN_19);
		M(_LT_ZZGEN_20); M(_LT_ZZGEN_21); M(_LT_ZZGEN_22);
		M(_LT_ZZGEN_23); M(_LT_ZZGEN_24); M(_LT_ZZGEN_25);
		M(_LT_ZZGEN_26); M(_LT_ZZGEN_27); M(_LT_ZZGEN_35);
		M(_LT_ZZNON_COMMERC2); M(_LT_SEE_COPYING_11);
		M(_LT_SEE_OUTPUT_1); M(_LT_SEE_README_9);
		M(_LT_Oracle_Berkeley_DB);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"distribut\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("licen", filetext, REG_ICASE)) {	/* match count 443 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"licen\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_Imlib2); M(_LT_OPEN_FONT_V10); M(_LT_OPEN_FONT_V11);
		M(_LT_OPEN_FONT_V10_1); M(_LT_OPEN_FONT_V11_1);
		M(_LT_ADAPTEC_GPL); M(_LT_ADAPTEC_OBJ); M(_LT_ADAPTIVE);
		M(_LT_ADOBE_1); M(_LT_ADOBE_4); M(_LT_ADOBE_5);
		M(_LT_ADOBE_6); M(_LT_ADOBE_7); M(_LT_ADOBE_EULA);
		M(_LT_ADOBE_OTHER); M(_LT_ADOBE_SRC); M(_LT_ADOBE_SUB);
		M(_LT_AFFERO1); M(_LT_AFFERO_V3); M(_LT_AFFEROref1);
		M(_LT_NOTAFFEROref1); M(_LT_AFL); M(_LT_AFLref2);
		M(_LT_AFPL); M(_LT_AGAINST_DRM); M(_LT_AGERE_EULA);
		M(_LT_ALGORITHMICS); M(_LT_ALADDIN_RESTRICT);
		M(_LT_AMD_EULA); M(_LT_APACHEref2); M(_LT_APACHEref3);
		M(_LT_APACHESTYLEref); M(_LT_APPLE_3); M(_LT_APPLE_4);
		M(_LT_APPLE_FONTFORGE); M(_LT_APSLref1);
		M(_LT_APTANA); M(_LT_ARPHIC); M(_LT_ARTIFEX);
		M(_LT_ARTref1); M(_LT_ARTref2); M(_LT_ARTref3);
		M(_LT_ARTref4); M(_LT_ARTref5); M(_LT_ARTref6);
		M(_LT_ART_V2); M(_LT_ASCENDER_EULA); M(_LT_ASL11ref);
		M(_LT_ASLref1); M(_LT_ASLref3); M(_LT_ASL);
		M(_LT_ASL20ref); M(_LT_ASL20ref_2); M(_LT_ASL20);
		M(_LT_ATI_EULA); M(_LT_ATT_1); M(_LT_ATT_SRC_2);
		M(_LT_BAEKMUK_2); M(_LT_BEA_1); M(_LT_BEA_2);
		M(_LT_BEERWARE); M(_LT_BISONref); M(_LT_BITSTREAM_2);
		M(_LT_BITTORRENT); M(_LT_BITTORRENTref);
		M(_LT_BITTORRENT_V11); M(_LT_BITTORRENT_V10);
		M(_LT_BOGUSTMPL); M(_LT_BOOST_GRAPH); M(_LT_BOOSTref1);
		M(_LT_BRAINSTORM_EULA); M(_LT_BROADCOM_EULA);
		M(_LT_BSDref1); M(_LT_BSDref2); M(_LT_BSDref3);
		M(_LT_BSDref4); M(_LT_BSDref5); M(_LT_BSDref6);
		M(_LT_BSDref7); M(_LT_BSDref8); M(_LT_BSDref9);
		M(_LT_BSDSTYLEref1); M(_LT_BSDSTYLEref2);
		M(_LT_BSDSTYLEref4); M(_LT_BSD_10); M(_LT_XML_DB_V10);
		M(_LT_BSD_CLAUSE_CLEAR); M(_LT_CA); M(_LT_CATHARON);
		M(_LT_CC_GPL); M(_LT_CCA_1); M(_LT_CCA_2);
		M(_LT_CCA_ref); M(_LT_CCA_SA); M(_LT_CCA_SAref);
		M(_LT_CCA_ND_ref); M(_LT_CCA_BY_V30); M(_LT_CCPL);
		M(_LT_CDDL); M(_LT_CDDL10ref); M(_LT_CDDLref);
		M(_LT_CECILL_1); M(_LT_CECILL_2_ref);
		M(_LT_CECILL_DUALref); M(_LT_CECILL_ref);
		M(_LT_CECILL_ref2); M(_LT_CECILL_B_ref);
		M(_LT_COMMERCIAL_1); M(_LT_COMPUSERVE); M(_LT_CMU_3);
		M(_LT_CMU_6); M(_LT_COPYLEFT_1); M(_LT_COPYLEFT_2);
		M(_LT_CPALref); M(_LT_CPAL_V1_ref); M(_LT_CPOL);
		M(_LT_CPL_2); M(_LT_CPLref1); M(_LT_CUPS_COMMERCIAL);
		M(_LT_CYLINK_ISC_1); M(_LT_CYLINK_ISC_2); M(_LT_CYPRESS);
		M(_LT_DARPA_COUGAAR); M(_LT_DEB_CONTRACT); M(_LT_DEC_2);
		M(_LT_DSCT); M(_LT_DSL); M(_LT_DUAL_LICENSE_1);
		M(_LT_DUAL_LICENSE_2); M(_LT_DUAL_LICENSE_4);
		M(_LT_DUAL_LICENSE_5); M(_LT_DUAL_LICENSE_7);
		M(_LT_DUAL_LICENSE_9); M(_LT_DUAL_LICENSE_10);
		M(_LT_DUAL_LICENSE_12); M(_LT_DYADE_2);
		M(_LT_ECL1); M(_LT_ECL2); M(_LT_ECLIPSEref);
		M(_LT_EDS_2); M(_LT_EGENIX_COM); M(_LT_EIFFEL_1);
		M(_LT_EIFFEL_20); M(_LT_EPSON_EULA); M(_LT_EXPORTS_USA);
		M(_LT_FEDORA); M(_LT_FEDORA_CLA); M(_LT_FREE_3);
		M(_LT_FREE_19); M(_LT_FREE_34); M(_LT_FREE_36);
		M(_LT_FREE_38); M(_LT_FREE_40); M(_LT_FREEART_V10);
		M(_LT_FREEART_V13); M(_LT_FREEPLref); M(_LT_FREEPLref_1);
		M(_LT_FREETYPE); M(_LT_FREETYPEref); M(_LT_LG);
		M(_LT_GCA); M(_LT_GENIVIAref); M(_LT_GEN_EULA);
		M(_LT_GEN_PROPRIETARY_2); M(_LT_GLIDE_GPL); M(_LT_GNU_2);
		M(_LT_GNU_4); M(_LT_GNU_PROJECTS); M(_LT_GOOGLE_2);
		M(_LT_GPDLref); M(_LT_GPL_ALT); M(_LT_GPL_EXCEPT_1);
		M(_LT_GPL_EXCEPT_2); M(_LT_GPL_EXCEPT_ECOS);
		M(_LT_GPL_FSF); M(_LT_GPL_META_DEBIAN); M(_LT_GPL_NAMED);
		M(_LT_GPL_NAMED_EXHIBIT); M(_LT_GPL_NAMED3_EXHIBIT);
		M(_LT_GPL_NAMED_COMPATIBLE); M(_LT_RPSL_COMPATIBLE);
		M(_LT_GPLref4); M(_LT_GPLref9); M(_LT_GPLref13);
		M(_LT_GPLref16); M(_LT_GPLref17); M(_LT_GPLref18);
		M(_LT_GPLref20); M(_LT_GPL_ref); M(_LT_GPL_V1);
		M(_LT_GPL_V2); M(_LT_GPL_V2_ref1); M(_LT_GPL_V2_ref);
		M(_LT_GPL_V3_ref); M(_LT_GPL3_NOT_AFFERO);
		M(_LT_GPL3_PATENTS); M(_LT_GPL3ref2); M(_LT_GPL3ref3);
		M(_LT_GPL3ref31); M(_LT_GS_GNU1); M(_LT_GS);
		M(_LT_GSOAPref13); M(_LT_GSOAPref); M(_LT_HACKTIVISMO);
		M(_LT_HAUPPAUGE); M(_LT_HELIX_TITLE); M(_LT_HP_EULA2);
		M(_LT_HP_EULA3); M(_LT_HP_EULA4); M(_LT_HP_IBM_1);
		M(_LT_HP_IBM_2); M(_LT_HP_4); M(_LT_HP_6);
		M(_LT_HP_PROPRIETARY_2); M(_LT_HP_PROPRIETARY_3);
		M(_LT_IBM_1); M(_LT_IBM_3); M(_LT_IBM_EULA);
		M(_LT_IBM_JIKES); M(_LT_IBM_PLref1); M(_LT_IBM_PIBS);
		M(_LT_IBM_RECIP); M(_LT_ID_EULA); M(_LT_IDPLref);
		M(_LT_IETF_3); M(_LT_INDEMN_1); M(_LT_INNERNETref_V2);
		M(_LT_INNERNETref); M(_LT_INTEL); M(_LT_INTEL_1);
		M(_LT_INTEL_2); M(_LT_INTEL_4); M(_LT_INTEL_5);
		M(_LT_INTEL_6); M(_LT_INTEL_7); M(_LT_INTEL_EULA);
		M(_LT_INTEL_RESTRICT); M(_LT_INTERLINK_EULA);
		M(_LT_IOSOFT_SRCONLY); M(_LT_IPA_EULA); M(_LT_IPTC);
		M(_LT_JABBER_1); M(_LT_JABBER_2); M(_LT_JAVA_WSDL_SCHEMA);
		M(_LT_JPEG_1); M(_LT_JPNIC); M(_LT_KDAB_2);
		M(_LT_KDE); M(_LT_KNUTH_2); M(_LT_LACHMAN_SECRET);
		M(_LT_LATEXref2); M(_LT_LATEXref4); M(_LT_LATEX_PREAMBLE);
		M(_LT_LATEXPL_3); M(_LT_LATEXPLref1); M(_LT_LATEXPLref2);
		M(_LT_LDPref2); M(_LT_LEGATO_2); M(_LT_LGPL_ALT);
		M(_LT_LGPLref6); M(_LT_LGPLref7); M(_LT_LGPLref8);
		M(_LT_LGPLref9); M(_LT_LGPL_3); M(_LT_LGPL_NAMED);
		M(_LT_LGPL_NAMED_EXHIBIT); M(_LT_MACROV_IA);
		M(_LT_MANDRIVA); M(_LT_METRO); M(_LT_METROLINKref);
		M(_LT_METRO_NONFREE); M(_LT_MIT_2); M(_LT_MIT_9);
		M(_LT_MIT_11); M(_LT_MITref1); M(_LT_MITref2);
		M(_LT_MOT_1); M(_LT_MOT_2); M(_LT_MPEG3); M(_LT_MPL_2);
		M(_LT_MPL_OR_MITX); M(_LT_MPLref1); M(_LT_MSCORP_EULA_2);
		M(_LT_MSCORP_EULA_4); M(_LT_MSCORP_EULA_5);
		M(_LT_MSCORP_IP_1); M(_LT_MSCORP_IP_2); M(_LT_MSCORP_PL);
		M(_LT_MSCORP_PLref1); M(_LT_MSCORP_PLref2);
		M(_LT_MSCORP_RLref); M(_LT_MSCORP_SSLref);
		M(_LT_MULTICORP_1); M(_LT_MULTICORP_2); M(_LT_NESSUS);
		M(_LT_NOKIA); M(_LT_NOTATT_NOTBSD); M(_LT_NOVELL);
		M(_LT_NPL_1); M(_LT_NPL_2); M(_LT_NVIDIA); M(_LT_ODL);
		M(_LT_OG_1); M(_LT_OG_2); M(_LT_OG_3); M(_LT_OG_PROP);
		M(_LT_OMRON1); M(_LT_ONTOPIA); M(_LT_OPENCONTENT);
		M(_LT_OPENLDAP_2); M(_LT_OPENMKT); M(_LT_OPENPUBLref);
		M(_LT_ORACLE_DEVEL); M(_LT_ORACLE_PROTO);
		M(_LT_OSD); M(_LT_OSL_BAD); M(_LT_OPENSSLref2);
		M(_LT_COMBINED_OPENSSL_SSLEAY); M(_LT_OSLref1);
		M(_LT_PERLref4); M(_LT_PHP_ref); M(_LT_PHPref1);
		M(_LT_PHP_V30_1); M(_LT_PHP_V30_2); M(_LT_PIXWARE_EULA);
		M(_LT_PNG_ZLIBref1); M(_LT_PNG_ZLIBref2);
		M(_LT_POLYSERVE); M(_LT_PRINCETON); M(_LT_PUBDOM_ODC);
		M(_LT_PYTHON_4); M(_LT_PYTHONref2); M(_LT_PYTHONref3);
		M(_LT_PYTHONSTYLEref); M(_LT_CNRI_PYTHON);
		M(_LT_CNRI_PYTHON_GPL); M(_LT_QT_COMMref);
		M(_LT_QUEST_EULA); M(_LT_REAL_RCSL); M(_LT_REAL_RCSLref);
		M(_LT_REAL_RPSL); M(_LT_REAL_RPSLref); M(_LT_RECIP_1);
		M(_LT_RECIP_2); M(_LT_RECV_GPL); M(_LT_RECV_LGPL);
		M(_LT_REDLAND); M(_LT_RH_1); M(_LT_RH_EULA);
		M(_LT_RH_FEDORA); M(_LT_RH_REDHAT); M(_LT_RH_PKGS);
		M(_LT_RH_SPECIFIC); M(_LT_RIVERBANK); M(_LT_RSA_2);
		M(_LT_RSA_3); M(_LT_RSA_4); M(_LT_SAX_PD);
		M(_LT_RUBYref1); M(_LT_RUBYref4); M(_LT_SCITECH);
		M(_LT_SCO_COMM); M(_LT_SEE_GPL); M(_LT_SEE_LGPL);
		M(_LT_SGI_2); M(_LT_SGI_GLXref); M(_LT_SGML);
		M(_LT_SNIA_PL); M(_LT_SNIAref); M(_LT_SPIKESOURCE);
		M(_LT_STANFORD); M(_LT_SUN_ANYagreement);
		M(_LT_SUN_BCLA_1); M(_LT_SUN_BCLA_2);
		M(_LT_SUN_BCLAref); M(_LT_SUN_ENTITLE);
		M(_LT_SUN_PLref); M(_LT_SUN_PROPRIETARY);
		M(_LT_SUN_SCSLref); M(_LT_SUN_SISSLref1);
		M(_LT_SUN_SISSLref2); M(_LT_SUN_RPC); M(_LT_SUN_3);
		M(_LT_SUN_4); M(_LT_SUN_GRAPHICS); M(_LT_SYBASE);
		M(_LT_TPLref); M(_LT_TRIDENT_EULA); M(_LT_TROLLTECH);
		M(_LT_UBC); M(_LT_UCWARE_EULA_1); M(_LT_UCWARE_EULA_2);
		M(_LT_UMICHIGAN_1); M(_LT_USGOVT_1); M(_LT_USGOVT_2);
		M(_LT_UW4); M(_LT_VIM_2); M(_LT_VMWARE); M(_LT_W3Cref1);
		M(_LT_W3Cref2); M(_LT_W3Cref3); M(_LT_W3Cref4);
		M(_LT_WINTERTREE); M(_LT_WTFPL); M(_LT_WTFPLref_1);
		M(_LT_WTFPLref); M(_LT_WU_FTPDref); M(_LT_X11_1);
		M(_LT_X11_4); M(_LT_X11_STYLE); M(_LT_XOPEN_1);
		M(_LT_ZONEALARM); M(_LT_ZZGEN_21); M(_LT_ZZGEN_28);
		M(_LT_ZZGEN_29); M(_LT_ZZGEN_30); M(_LT_SEE_COPYING_1);
		M(_LT_SEE_COPYING_3); M(_LT_SEE_COPYING_9);
		M(_LT_SEE_COPYING_10); M(_LT_SEE_COPYING_13);
		M(_LT_SEE_COPYING_14); M(_LT_SEE_OTHER_1);
		M(_LT_SEE_OTHER_4); M(_LT_SEE_OTHER_8);
		M(_LT_SEE_LICENSE_1); M(_LT_SEE_LICENSE_3);
		M(_LT_SEE_LICENSE_9); M(_LT_SEE_LICENSE_11);
		M(_LT_SEE_LICENSE_12); M(_LT_SEE_LICENSE_13);
		M(_LT_SEE_README_1); M(_LT_SEE_README_3); M(_LT_XFREE86);
		M(_LT_XFREE86_V10); M(_LT_XFREE86_V11); M(_LT_MX4J_V10);
		M(_LT_MX4J); M(_LT_LIBGCJ); M(_LT_Interbase_V10);
		M(_LT_KnowledgeTree_V11); M(_LT_FTL); M(_LT_ClearSilver);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"licen\":");
#endif	/* LTSR_DEBUG */
	if (!strGrep("[iu][nst]", filetext, REG_ICASE)) {	/* match count 887 */
#ifdef	LTSR_DEBUG
		printf("DEBUG: eliminate searches for \"[iu][nst]\"\n");
#endif	/* LTSR_DEBUG */
		M(_LT_Imlib2); M(_LT_OPEN_FONT_V10_1);
		M(_LT_OPEN_FONT_V11_1); M(_LT_ACAA_RIGHTS); M(_LT_ACDL);
		M(_LT_ADAPTEC_GPL); M(_LT_ADAPTEC_OBJ); M(_LT_ADAPTIVE);
		M(_LT_ADOBE_1); M(_LT_ADOBE_2); M(_LT_ADOBE_3);
		M(_LT_ADOBE_4); M(_LT_ADOBE_5); M(_LT_ADOBE_6);
		M(_LT_ADOBE_7); M(_LT_ADOBE_AFM); M(_LT_ADOBE_DATA);
		M(_LT_ADOBE_EULA); M(_LT_ADOBE_OTHER); M(_LT_ADOBE_SRC);
		M(_LT_ADOBE_SUB); M(_LT_AFFERO1); M(_LT_AFFERO2);
		M(_LT_AFFERO3); M(_LT_AFFERO_V3); M(_LT_AFFEROref1);
		M(_LT_AFFEROref2); M(_LT_NOTAFFEROref1);
		M(_LT_AFL); M(_LT_AFLref1); M(_LT_AFPL);
		M(_LT_AGAINST_DRM); M(_LT_AGE); M(_LT_AGERE_EULA);
		M(_LT_AGFA); M(_LT_AGFA_EULA); M(_LT_ALGORITHMICS);
		M(_LT_ALADDIN_RESTRICT); M(_LT_AMD); M(_LT_AMD_EULA);
		M(_LT_AOL_EULA); M(_LT_APACHE_1); M(_LT_APACHE_2);
		M(_LT_APACHEref1); M(_LT_APACHEref2); M(_LT_APACHEref3);
		M(_LT_APACHESTYLEref); M(_LT_APPLE_1); M(_LT_APPLE_2);
		M(_LT_APPLE_3); M(_LT_APPLE_4); M(_LT_APPLE_FONTFORGE);
		M(_LT_APPLE_SAMPLE); M(_LT_APSLref2); M(_LT_APTANA);
		M(_LT_ARPHIC); M(_LT_ARJ); M(_LT_ARTIFEX);
		M(_LT_ARTref1); M(_LT_ARTref2); M(_LT_ARTref3);
		M(_LT_ARTref4); M(_LT_ARTref5); M(_LT_ARTref6);
		M(_LT_ART_2); M(_LT_ART_V2); M(_LT_ASCENDER_EULA);
		M(_LT_ASLref2); M(_LT_ASLref3); M(_LT_ASL);
		M(_LT_ASL20ref); M(_LT_ASL20ref_2); M(_LT_ASL20);
		M(_LT_ATI_EULA); M(_LT_ATMEL); M(_LT_ATT_1);
		M(_LT_ATT_2); M(_LT_ATT_SRC_1); M(_LT_ATT_SRC_2);
		M(_LT_ATT_NONCOMMERC1); M(_LT_ATT_NONCOMMERC2);
		M(_LT_ATTRIB); M(_LT_AVM_1); M(_LT_AVM_2); M(_LT_AVM_3);
		M(_LT_BAEKMUK_1); M(_LT_BAEKMUK_2); M(_LT_BANCTEC);
		M(_LT_BEA_1); M(_LT_BEA_2); M(_LT_BEERWARE);
		M(_LT_BELLCORE); M(_LT_BH_FONT); M(_LT_BISON);
		M(_LT_BISONref); M(_LT_BITSTREAM_2); M(_LT_BITTORRENT);
		M(_LT_BITTORRENTref); M(_LT_BITTORRENT_V11);
		M(_LT_BITTORRENT_V10); M(_LT_BIZNET); M(_LT_BOGUSTMPL);
		M(_LT_BOOST_1); M(_LT_BOOST_2); M(_LT_BOOST_LAMBDA);
		M(_LT_BRAINSTORM_EULA); M(_LT_BROADCOM_EULA);
		M(_LT_BSDref2); M(_LT_BSDref3); M(_LT_BSDref4);
		M(_LT_BSDref5); M(_LT_BSDref6); M(_LT_BSDSTYLEref1);
		M(_LT_BSDSTYLEref2); M(_LT_BSDSTYLEref3); M(_LT_BSD_1);
		M(_LT_BSD_2); M(_LT_BSD_3); M(_LT_BSD_4); M(_LT_BSD_5);
		M(_LT_BSD_6); M(_LT_BSD_7); M(_LT_BSD_8); M(_LT_BSD_9);
		M(_LT_BSD_10); M(_LT_BSD_11); M(_LT_BSD_12);
		M(_LT_BSD_13); M(_LT_BSD_NONC); M(_LT_BSD_CLAUSE_0);
		M(_LT_BSD_CLAUSE_1); M(_LT_BSD_CLAUSE_2);
		M(_LT_BSD_CLAUSE_3); M(_LT_BSD_CLAUSE_4);
		M(_LT_XML_DB_V10); M(_LT_BSD_CLAUSE_CLEAR);
		M(_LT_FREE_BSD); M(_LT_CA); M(_LT_CADENCE);
		M(_LT_CAMBRIDGE); M(_LT_CATHARON); M(_LT_CC_GPL);
		M(_LT_CCA_1); M(_LT_CCA_2); M(_LT_CCA_ref);
		M(_LT_CCA_SA); M(_LT_CCA_SAref); M(_LT_CCA_NC_30);
		M(_LT_CCA_ND_30); M(_LT_CCA_ND_ref); M(_LT_CCA_BY_V30);
		M(_LT_CCPL); M(_LT_CDDL); M(_LT_CDDL10ref);
		M(_LT_CDDLref); M(_LT_CECILL_1); M(_LT_CECILL_2);
		M(_LT_CECILL_2_ref); M(_LT_CECILL_DUALref);
		M(_LT_CECILL_ref); M(_LT_CECILL_ref1); M(_LT_CECILL_ref2);
		M(_LT_CECILL_B_ref); M(_LT_CISCO); M(_LT_COLUMBIA);
		M(_LT_COMMERCIAL_1); M(_LT_COMMERCIAL_2); M(_LT_COMPAQ_1);
		M(_LT_COMPAQ_EULA); M(_LT_COMPUSERVE); M(_LT_CMU_1);
		M(_LT_CMU_2); M(_LT_CMU_3); M(_LT_CMU_4); M(_LT_CMU_5);
		M(_LT_CMU_6); M(_LT_COMTROL); M(_LT_COPYLEFT_1);
		M(_LT_COPYLEFT_2); M(_LT_CPALref); M(_LT_CPAL_V1_ref);
		M(_LT_CPOL); M(_LT_CPL_1); M(_LT_CPL_2); M(_LT_CUPS);
		M(_LT_CUPS_COMMERCIAL); M(_LT_CYLINK_ISC_1);
		M(_LT_CYLINK_ISC_2); M(_LT_DARPA); M(_LT_DARPA_COUGAAR);
		M(_LT_DEB_CONTRACTref); M(_LT_DEC_1); M(_LT_DEC_2);
		M(_LT_DELAWARE); M(_LT_DOCBOOK); M(_LT_DMTF); M(_LT_DPTC);
		M(_LT_DSCT); M(_LT_DSL); M(_LT_DUAL_LICENSE_1);
		M(_LT_DUAL_LICENSE_2); M(_LT_DUAL_LICENSE_3);
		M(_LT_DUAL_LICENSE_3_EXHIBIT); M(_LT_DUAL_LICENSE_4);
		M(_LT_DUAL_LICENSE_6); M(_LT_DUAL_LICENSE_7);
		M(_LT_DUAL_LICENSE_8); M(_LT_DUAL_LICENSE_10);
		M(_LT_DUAL_LICENSE_11); M(_LT_DUAL_LICENSE_12);
		M(_LT_DYADE); M(_LT_EBT); M(_LT_ECL); M(_LT_ECL1);
		M(_LT_ECL2); M(_LT_ECLIPSEref); M(_LT_EDINBURGH_1);
		M(_LT_EDINBURGH_2); M(_LT_EDS_1); M(_LT_EDS_2);
		M(_LT_EIFFEL); M(_LT_EIFFEL_1); M(_LT_EPINIONS);
		M(_LT_EPSON_EULA); M(_LT_EPSON_PL); M(_LT_EU);
		M(_LT_EXCEPT_1); M(_LT_EXPORTS_USA); M(_LT_FAIR);
		M(_LT_FEDORA); M(_LT_FEDORA_CLA); M(_LT_FRAME);
		M(_LT_FRAMEWORX); M(_LT_FREE_1); M(_LT_FREE_2);
		M(_LT_FREE_3); M(_LT_FREE_4); M(_LT_FREE_5);
		M(_LT_FREE_6); M(_LT_FREE_7); M(_LT_FREE_8);
		M(_LT_FREE_9); M(_LT_FREE_10); M(_LT_FREE_11);
		M(_LT_FREE_12); M(_LT_FREE_13); M(_LT_FREE_14);
		M(_LT_FREE_15); M(_LT_FREE_16); M(_LT_FREE_17);
		M(_LT_FREE_18); M(_LT_FREE_19); M(_LT_FREE_20);
		M(_LT_FREE_21); M(_LT_FREE_22); M(_LT_FREE_23);
		M(_LT_FREE_24); M(_LT_FREE_25); M(_LT_FREE_26);
		M(_LT_FREE_27); M(_LT_FREE_28); M(_LT_FREE_29);
		M(_LT_FREE_30); M(_LT_FREE_31); M(_LT_FREE_32);
		M(_LT_FREE_33); M(_LT_FREE_34); M(_LT_FREE_35);
		M(_LT_FREE_36); M(_LT_FREE_37); M(_LT_FREE_38);
		M(_LT_FREE_39); M(_LT_FREE_40); M(_LT_FREE_41);
		M(_LT_FREE_42); M(_LT_FREE_43); M(_LT_FREE_44);
		M(_LT_FREE_45); M(_LT_FREE_46); M(_LT_FREE_47);
		M(_LT_FREE_48); M(_LT_FREE_49); M(_LT_FREE_50);
		M(_LT_FREE_51); M(_LT_FREE_52); M(_LT_FREE_53);
		M(_LT_FREE_54); M(_LT_FREE_55); M(_LT_FREE_56);
		M(_LT_FREE_57); M(_LT_FREE_58); M(_LT_FREE_59);
		M(_LT_FREE_60); M(_LT_FREE_61); M(_LT_FREE_62);
		M(_LT_FREE_63); M(_LT_FREE_64); M(_LT_FREE_65);
		M(_LT_FREE_66); M(_LT_FREE_67); M(_LT_FREE_68);
		M(_LT_FREE_69); M(_LT_FREE_70); M(_LT_FREE_71);
		M(_LT_FREE_72); M(_LT_FREE_73); M(_LT_FREE_74);
		M(_LT_FREE_75); M(_LT_FREE_77); M(_LT_FREE_78);
		M(_LT_FREE_79); M(_LT_FREE_81); M(_LT_FREE_82);
		M(_LT_FREE_83); M(_LT_FREE_84); M(_LT_FREE_85);
		M(_LT_FREEART_V10); M(_LT_FREEART_V13);
		M(_LT_FREEPL); M(_LT_FREE_SW); M(_LT_FREETYPE);
		M(_LT_FREETYPEref); M(_LT_FSF_1); M(_LT_FSF_2);
		M(_LT_FSF_3); M(_LT_FSF_4); M(_LT_FSF_5);
		M(_LT_FSFref1); M(_LT_FSFref2); M(_LT_GARMIN_EULA);
		M(_LT_GCA); M(_LT_GENIVIAref); M(_LT_GEN_EULA);
		M(_LT_GEN_IP_1); M(_LT_GEN_IP_2); M(_LT_GEN_IP_3);
		M(_LT_GEN_PROPRIETARY_1); M(_LT_GEN_PROPRIETARY_2);
		M(_LT_GEN_PROPRIETARY_3); M(_LT_GFDLref1); M(_LT_GFDL);
		M(_LT_GLIDE_3DFX); M(_LT_GLIDE_GPL); M(_LT_GNU_COPYLEFT);
		M(_LT_GNU_1); M(_LT_GNU_3); M(_LT_GNU_PROJECTS);
		M(_LT_GOOGLE_1); M(_LT_GOOGLE_2); M(_LT_GPDLref);
		M(_LT_GPL_ALT); M(_LT_GPL_EXCEPT_1); M(_LT_GPL_EXCEPT_2);
		M(_LT_GPL_EXCEPT_CLASSPATH_2); M(_LT_GPL_EXCEPT_AUTOCONF);
		M(_LT_GPL_EXCEPT_AUTOCONF_2); M(_LT_GPL_EXCEPT_BISON_1);
		M(_LT_GPL_EXCEPT_BISON_2); M(_LT_GPL_EXCEPT_ECOS);
		M(_LT_GPL_FONT1); M(_LT_GPL_FONT2); M(_LT_GPL_FSF);
		M(_LT_GPL_META_DEBIAN); M(_LT_GPL_NAMED_EXHIBIT);
		M(_LT_GPL_NAMED_COMPATIBLE); M(_LT_GPLpatt1);
		M(_LT_GPLpatt2); M(_LT_GPLref1); M(_LT_GPLref2);
		M(_LT_GPLref3); M(_LT_GPLref4); M(_LT_GPLref5);
		M(_LT_GPLref6); M(_LT_GPLref8); M(_LT_GPLref9);
		M(_LT_GPLref10); M(_LT_GPLref11); M(_LT_GPLref12);
		M(_LT_GPLref18); M(_LT_GPLref20); M(_LT_GPL_ref);
		M(_LT_GPL_V1); M(_LT_GPL_V2); M(_LT_GPL_V2_ref1);
		M(_LT_GPL_V2_ref); M(_LT_GPL_V3_ref);
		M(_LT_GPL_1); M(_LT_GPL_2); M(_LT_GPL3_NOT_AFFERO);
		M(_LT_GPL3_PATENTS); M(_LT_GPL3ref); M(_LT_GPL3ref2);
		M(_LT_GPL3ref3); M(_LT_GPL3ref31); M(_LT_FORMER_GNU);
		M(_LT_FREEBSD_DOC); M(_LT_GS_GNU1); M(_LT_GS_GNU2);
		M(_LT_GS); M(_LT_HACKTIVISMO); M(_LT_HAUPPAUGE);
		M(_LT_HELIX_TITLE); M(_LT_HP_EULA1); M(_LT_HP_EULA2);
		M(_LT_HP_EULA3); M(_LT_HP_IBM_1); M(_LT_HP_IBM_2);
		M(_LT_HP_1); M(_LT_HP_3); M(_LT_HP_4); M(_LT_HP_5);
		M(_LT_HP_6); M(_LT_HP_7); M(_LT_HP_DEC);
		M(_LT_HP_PROPRIETARY_1); M(_LT_HP_PROPRIETARY_2);
		M(_LT_HP_PROPRIETARY_3); M(_LT_IBM_1); M(_LT_IBM_2);
		M(_LT_IBM_3); M(_LT_IBM_COURIER); M(_LT_IBM_EULA);
		M(_LT_IBM_OWNER); M(_LT_IBM_PLref1); M(_LT_IBM_PIBS);
		M(_LT_IBM_RECIP); M(_LT_ID_EULA); M(_LT_IDPLref);
		M(_LT_IEEE_DOC); M(_LT_IETF_1); M(_LT_IETF_2);
		M(_LT_IETF_3); M(_LT_IETF_4); M(_LT_IMAGEMAGICK);
		M(_LT_INDEMN_1); M(_LT_INDEMN_3); M(_LT_INDEMN_4);
		M(_LT_INDEMN_8); M(_LT_INDEMN_9); M(_LT_INDEMN_10);
		M(_LT_INDEMN_11); M(_LT_INDEMN_12); M(_LT_INDEMN_13);
		M(_LT_INDEMN_14); M(_LT_INFOSEEK); M(_LT_INNERNET);
		M(_LT_INNERNETref_V2); M(_LT_INNERNETref); M(_LT_INTEL);
		M(_LT_INTEL_1); M(_LT_INTEL_2); M(_LT_INTEL_3);
		M(_LT_INTEL_4); M(_LT_INTEL_5); M(_LT_INTEL_6);
		M(_LT_INTEL_7); M(_LT_INTEL_EULA); M(_LT_INTEL_FW);
		M(_LT_INTEL_RESTRICT); M(_LT_INTERLINK_EULA);
		M(_LT_INTRANET_ONLY); M(_LT_NOT_INTERNET); M(_LT_IOS);
		M(_LT_IOSOFT_SRCONLY); M(_LT_IPA_EULA); M(_LT_IPTC);
		M(_LT_IRONDOC); M(_LT_JABBER_1); M(_LT_JABBER_2);
		M(_LT_JAVA_WSDL4J); M(_LT_JAVA_WSDL_ENUM);
		M(_LT_JAVA_WSDL_POLICY); M(_LT_JAVA_WSDL_SCHEMA);
		M(_LT_JPEG_1); M(_LT_JPEG_2); M(_LT_JPNIC); M(_LT_KDAB_1);
		M(_LT_KDAB_2); M(_LT_KDE); M(_LT_KEYSPAN); M(_LT_KNUTH_1);
		M(_LT_KNUTH_2); M(_LT_KNUTH_STYLE); M(_LT_LACHMAN_SECRET);
		M(_LT_LARABIE_EULA); M(_LT_LATEXref1); M(_LT_LATEXref2);
		M(_LT_LATEXref3); M(_LT_LATEXref4); M(_LT_LATEXref5);
		M(_LT_LATEX); M(_LT_LATEX_PREAMBLE); M(_LT_LATEXPL_1);
		M(_LT_LATEXPL_2); M(_LT_LATEXPL_3); M(_LT_LATEXPLref1);
		M(_LT_LATEXPLref2); M(_LT_LATEXPLref3); M(_LT_LDP);
		M(_LT_LDPref1); M(_LT_LDPref2); M(_LT_LEGATO_1);
		M(_LT_LEGATO_2); M(_LT_LGPL_ALT); M(_LT_LGPLref1);
		M(_LT_LGPLref2); M(_LT_LGPLref3); M(_LT_LGPLref4);
		M(_LT_LGPLref5); M(_LT_LGPLref10); M(_LT_LGPLrefFSF);
		M(_LT_LGPL_1); M(_LT_LGPL_2); M(_LT_LGPL_3);
		M(_LT_LGPL3ref); M(_LT_LGPL_NAMED_EXHIBIT);
		M(_LT_UNRARref1); M(_LT_UNRARref2); M(_LT_LINUXDOC);
		M(_LT_LINUX_HOWTO); M(_LT_MACROV_IA); M(_LT_MANDRIVA);
		M(_LT_MANPAGE); M(_LT_MELLANOX); M(_LT_METRO);
		M(_LT_METROLINKref); M(_LT_METRO_NONFREE); M(_LT_MIBBLE);
		M(_LT_MITDOC); M(_LT_MIT_0); M(_LT_MIT_1); M(_LT_MIT_2);
		M(_LT_MIT_3); M(_LT_MIT_4); M(_LT_MIT_5); M(_LT_MIT_6);
		M(_LT_MIT_7); M(_LT_MIT_8); M(_LT_MIT_9); M(_LT_MIT_10);
		M(_LT_MIT_11); M(_LT_MITref1); M(_LT_MITref2);
		M(_LT_MITEM); M(_LT_MITRE_1); M(_LT_MITRE_2);
		M(_LT_MOT_2); M(_LT_MPEG3); M(_LT_MPL_1); M(_LT_MPL_2);
		M(_LT_MPL_OR_MITX); M(_LT_MSCORP_1); M(_LT_MSCORP_2);
		M(_LT_MSCORP_3); M(_LT_MSCORP_4); M(_LT_MSCORP_5);
		M(_LT_MSCORP_EULA_1); M(_LT_MSCORP_EULA_2);
		M(_LT_MSCORP_EULA_3); M(_LT_MSCORP_EULA_4);
		M(_LT_MSCORP_INDEMNIFY); M(_LT_MSCORP_IP_1);
		M(_LT_MSCORP_IP_2); M(_LT_MSCORP_LIMITED);
		M(_LT_MSCORP_PL); M(_LT_MSCORPref1); M(_LT_MSCORP_PLref1);
		M(_LT_MSCORP_PLref2); M(_LT_MSCORP_REFLIC);
		M(_LT_MSCORP_RL); M(_LT_MSCORP_RLref);
		M(_LT_MSCORP_SSLref); M(_LT_MULTICORP_1);
		M(_LT_MULTICORP_2); M(_LT_MULTICS); M(_LT_MYSQL_EXCEPT);
		M(_LT_NASA); M(_LT_NCIPHER); M(_LT_ND_1);
		M(_LT_ND_2); M(_LT_ND_3); M(_LT_NESSUS); M(_LT_NOKIA);
		M(_LT_NONPROFIT_1); M(_LT_NOTATT_NOTBSD); M(_LT_NOT_FREE);
		M(_LT_NOVELL); M(_LT_NOVELL_IP_1); M(_LT_NOVELL_IP_2);
		M(_LT_NPL_1); M(_LT_NPL_2); M(_LT_NP_AME); M(_LT_NTP);
		M(_LT_NVIDIA); M(_LT_NVIDIA_EULA); M(_LT_NVIDIA_EULA_2);
		M(_LT_OCLC); M(_LT_ODL); M(_LT_OG_1); M(_LT_OG_2);
		M(_LT_OG_3); M(_LT_OG_PROP); M(_LT_OMRON1); M(_LT_OMRON2);
		M(_LT_ONTOPIA); M(_LT_OPENCONTENT); M(_LT_OPENLDAP_1);
		M(_LT_OPENLDAP_2); M(_LT_OPENMKT); M(_LT_OPENPUBL_1);
		M(_LT_OPENPUBL_2); M(_LT_ORACLE_DEVEL);
		M(_LT_ORACLE_PROTO); M(_LT_OREILLY_1); M(_LT_OREILLY_2);
		M(_LT_OSD); M(_LT_OSF_1); M(_LT_OSF_2); M(_LT_OSL_BAD);
		M(_LT_OPENSSLref1); M(_LT_OPENSSLref2); M(_LT_OSLref1);
		M(_LT_OSLref2); M(_LT_PARADIGM); M(_LT_PERLref1);
		M(_LT_PERLref2); M(_LT_PERLref3); M(_LT_PERL_1);
		M(_LT_PERL_2); M(_LT_PERL_3); M(_LT_PHP);
		M(_LT_PHP_ref); M(_LT_PHPref1); M(_LT_PIRIFORM);
		M(_LT_PIXWARE_EULA); M(_LT_PNG_ZLIB_1); M(_LT_PNG_ZLIB_2);
		M(_LT_PNG_ZLIBref1); M(_LT_PNG_ZLIBref3); M(_LT_POWDER);
		M(_LT_PRINCETON); M(_LT_PUBDOM_CC); M(_LT_UNLIN);
		M(_LT_PUBDOM_1); M(_LT_NOTPUBDOM_1); M(_LT_PUBDOM_7);
		M(_LT_PUBDOMNOTcpyrt); M(_LT_PUBDOM_NOTclaim);
		M(_LT_PUBDOM_ODC); M(_LT_PUBDOM_PDD); M(_LT_PUBDOM_USE);
		M(_LT_PUBLIC); M(_LT_PUBLIC_USE); M(_LT_PYTHON_1);
		M(_LT_PYTHON_2); M(_LT_PYTHON_3); M(_LT_PYTHON_4);
		M(_LT_PYTHONref1); M(_LT_PYTHONref2); M(_LT_QUALCOMM);
		M(_LT_QUARTERDECK); M(_LT_QPL); M(_LT_QPLref);
		M(_LT_QUEST_EULA); M(_LT_REAL_RCSL); M(_LT_REAL_RCSLref);
		M(_LT_REAL_RPSL); M(_LT_RECIP15); M(_LT_RECIP_1);
		M(_LT_RECIP_2); M(_LT_RECV_GPL); M(_LT_RECV_LGPL);
		M(_LT_REDLAND); M(_LT_RH_1); M(_LT_RH_EULA);
		M(_LT_RH_NONCOMMERCIAL); M(_LT_RH_PKGS); M(_LT_RICOH);
		M(_LT_RIVERBANK); M(_LT_RSA_1); M(_LT_RSA_2);
		M(_LT_RSA_3); M(_LT_RSA_4); M(_LT_RSA_5); M(_LT_RUBY);
		M(_LT_RUBYref1); M(_LT_RUBYref2); M(_LT_RUBYref3);
		M(_LT_RUBYref4); M(_LT_RUBYref5); M(_LT_SAME_LICENSE_1);
		M(_LT_SAME_LICENSE_2); M(_LT_SCITECH); M(_LT_SCO_COMM);
		M(_LT_SGI_1); M(_LT_SGI_2); M(_LT_SGI_FREEW);
		M(_LT_SGI_GLX); M(_LT_SGI_PROPRIETARY);
		M(_LT_SGML); M(_LT_SKYPE); M(_LT_SLEEPYCAT_NC);
		M(_LT_SNIA_PL); M(_LT_SPI); M(_LT_SPIKESOURCE);
		M(_LT_SRA); M(_LT_SSLEAY); M(_LT_SUN_ANYagreement);
		M(_LT_SUN_BCLA_1); M(_LT_SUN_BCLA_2); M(_LT_SUN_BCLAref);
		M(_LT_SUN_ENTITLE); M(_LT_SUN_IP); M(_LT_SUN_JAVA);
		M(_LT_SUN_PLref); M(_LT_SUN_PROPRIETARY); M(_LT_SUN_SCA);
		M(_LT_SUN_SCSL_TSA); M(_LT_SUN_SCSLref);
		M(_LT_SUN_SISSLref1); M(_LT_SUN_SISSLref2);
		M(_LT_SUN_PRO); M(_LT_SUN_RPC); M(_LT_SUNrestrict);
		M(_LT_SUN_1); M(_LT_SUN_2); M(_LT_SUN_3); M(_LT_SUN_4);
		M(_LT_SUN_5); M(_LT_SUN_6); M(_LT_SUN_GRAPHICS);
		M(_LT_SUN_NC); M(_LT_SYBASE); M(_LT_TEKTRONIX);
		M(_LT_TEX_EXCEPT); M(_LT_TRIDENT_EULA); M(_LT_TROLLTECH);
		M(_LT_UBC); M(_LT_UCAR_1); M(_LT_UCHICAGO);
		M(_LT_UCWARE_EULA_1); M(_LT_UCWARE_EULA_2); M(_LT_USC);
		M(_LT_UMICHIGAN_1); M(_LT_UMICHIGAN_2); M(_LT_UMONASH);
		M(_LT_UNICODE_1); M(_LT_UNICODE_2); M(_LT_UNICODE_3);
		M(_LT_USGOVT_1); M(_LT_USGOVT_2); M(_LT_USGOVT_RIGHTS1);
		M(_LT_USGOVT_RIGHTS2); M(_LT_USC_NC); M(_LT_USL_EUR);
		M(_LT_UUTAH); M(_LT_UW1); M(_LT_UW2); M(_LT_UW3);
		M(_LT_UW4); M(_LT_VIM_1); M(_LT_VIM_2); M(_LT_VIXIE);
		M(_LT_VMWARE); M(_LT_W3C_1); M(_LT_W3C_2); M(_LT_W3C_3);
		M(_LT_W3C_4); M(_LT_W3C_5); M(_LT_W3C_6); M(_LT_W3C_7);
		M(_LT_W3Cref2); M(_LT_W3Cref3); M(_LT_WINTERTREE);
		M(_LT_WTFPL); M(_LT_WTFPLref); M(_LT_WU_FTPD);
		M(_LT_WU_FTPDref); M(_LT_X11_1); M(_LT_X11_2);
		M(_LT_X11_3); M(_LT_X11_4); M(_LT_X11_STYLE);
		M(_LT_XEROX_1); M(_LT_XEROX_2); M(_LT_XIMIAN);
		M(_LT_XOPEN_1); M(_LT_XOPEN_2); M(_LT_YAHOO_1);
		M(_LT_YAHOO_BINARY); M(_LT_ZEUS); M(_LT_ZONEALARM);
		M(_LT_ZVENO); M(_LT_ZZGEN_1); M(_LT_ZZGEN_2);
		M(_LT_ZZGEN_3); M(_LT_ZZGEN_4); M(_LT_ZZGEN_5);
		M(_LT_ZZGEN_6); M(_LT_ZZGEN_7); M(_LT_ZZGEN_8);
		M(_LT_ZZGEN_10); M(_LT_ZZGEN_11); M(_LT_ZZGEN_12);
		M(_LT_ZZGEN_13); M(_LT_ZZGEN_14); M(_LT_ZZGEN_15);
		M(_LT_ZZGEN_16); M(_LT_ZZGEN_17); M(_LT_ZZGEN_18);
		M(_LT_ZZGEN_19); M(_LT_ZZGEN_20); M(_LT_ZZGEN_21);
		M(_LT_ZZGEN_22); M(_LT_ZZGEN_23); M(_LT_ZZGEN_24);
		M(_LT_ZZGEN_25); M(_LT_ZZGEN_26); M(_LT_ZZGEN_27);
		M(_LT_ZZGEN_28); M(_LT_ZZGEN_29); M(_LT_ZZGEN_31);
		M(_LT_ZZGEN_33); M(_LT_ZZGEN_34); M(_LT_ZZGEN_35);
		M(_LT_ZZGEN_36); M(_LT_ZZGEN_37); M(_LT_ZZGEN_38);
		M(_LT_ZZNON_COMMERC2); M(_LT_SEE_COPYING_1);
		M(_LT_SEE_COPYING_2); M(_LT_SEE_COPYING_3);
		M(_LT_SEE_COPYING_4); M(_LT_SEE_COPYING_5);
		M(_LT_SEE_COPYING_6); M(_LT_SEE_COPYING_7);
		M(_LT_SEE_COPYING_8); M(_LT_SEE_COPYING_9);
		M(_LT_SEE_COPYING_10); M(_LT_SEE_COPYING_11);
		M(_LT_SEE_COPYING_12); M(_LT_SEE_COPYING_13);
		M(_LT_SEE_COPYING_14); M(_LT_SEE_COPYING_15);
		M(_LT_SEE_COPYING_FINAL3); M(_LT_SEE_OTHER_1);
		M(_LT_SEE_OTHER_2); M(_LT_SEE_OTHER_3);
		M(_LT_SEE_OTHER_6); M(_LT_SEE_OTHER_7);
		M(_LT_SEE_OTHER_8); M(_LT_SEE_OTHER_9);
		M(_LT_SEE_OTHER_10); M(_LT_SEE_OTHER_11);
		M(_LT_SEE_OTHER_12); M(_LT_SEE_LICENSE_1);
		M(_LT_SEE_LICENSE_2); M(_LT_SEE_LICENSE_3);
		M(_LT_SEE_LICENSE_4); M(_LT_SEE_LICENSE_5);
		M(_LT_SEE_LICENSE_6); M(_LT_SEE_LICENSE_7);
		M(_LT_SEE_LICENSE_8); M(_LT_SEE_LICENSE_9);
		M(_LT_SEE_LICENSE_11); M(_LT_SEE_LICENSE_12);
		M(_LT_SEE_LICENSE_13); M(_LT_SEE_LICENSE_FINAL3);
		M(_LT_SEE_OUTPUT_1); M(_LT_SEE_README_1);
		M(_LT_SEE_README_2); M(_LT_SEE_README_3);
		M(_LT_SEE_README_4); M(_LT_SEE_README_5);
		M(_LT_SEE_README_6); M(_LT_SEE_README_7);
		M(_LT_SEE_README_8); M(_LT_SEE_README_9);
		M(_LT_SEE_README_FINAL3); M(_LT_XFREE86); M(_LT_MX4J_V10);
		M(_LT_MX4J); M(_LT_Oracle_Berkeley_DB); M(_LT_LIBGCJ);
		M(_LT_Interbase_V10); M(_LT_FTL); M(_LT_ClearSilver);
	}
#ifdef	LTSR_DEBUG
	showLTCache("Cache after cuts for \"[iu][nst]\":");
#endif	/* LTSR_DEBUG */
	return;
}
