# SPDX-FileCopyrightText: 2026 Contributors to FOSSology
# SPDX-License-Identifier: GPL-2.0-only

import sys
import os
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from nirjas.comment_classifier import (
    classify_comment,
    classify_batch,
    filter_license_comments,
    CommentClass,
)


class TestLicenseClassification(unittest.TestCase):

    def test_spdx_identifier(self):
        self.assertEqual(classify_comment("// SPDX-License-Identifier: MIT"), CommentClass.LICENSE)

    def test_apache_header(self):
        self.assertEqual(classify_comment("// Licensed under the Apache License, Version 2.0"), CommentClass.LICENSE)

    def test_mit_permission_grant(self):
        self.assertEqual(classify_comment("// Permission is hereby granted, free of charge, to any person"), CommentClass.LICENSE)

    def test_gpl_reference(self):
        self.assertEqual(classify_comment("// See the GNU General Public License for more details"), CommentClass.LICENSE)

    def test_copyright_with_year(self):
        self.assertEqual(classify_comment("// Copyright (c) 2024 Acme Corp"), CommentClass.LICENSE)

    def test_copyright_unicode(self):
        self.assertEqual(classify_comment("// Copyright \u00a9 2023 FOSSology Contributors"), CommentClass.LICENSE)

    def test_redistribution_clause(self):
        self.assertEqual(classify_comment("// Redistribution and use in source and binary forms"), CommentClass.LICENSE)

    def test_without_warranty(self):
        self.assertEqual(classify_comment("// Distributed without warranty of any kind"), CommentClass.LICENSE)

    def test_bsd_license(self):
        self.assertEqual(classify_comment("// Released under the BSD License"), CommentClass.LICENSE)

    def test_file_compliance(self):
        self.assertEqual(classify_comment("// You may not use this file except in compliance"), CommentClass.LICENSE)


class TestFalsePositiveGuards(unittest.TestCase):

    def test_license_manager_class(self):
        self.assertEqual(classify_comment("// LicenseManager handles auth"), CommentClass.DEV_COMMENT)

    def test_copyright_year_variable(self):
        self.assertEqual(classify_comment("// copyrightYear = 2024"), CommentClass.DEV_COMMENT)

    def test_get_license_function(self):
        self.assertEqual(classify_comment("# getLicenseFromDB() returns cached value"), CommentClass.DEV_COMMENT)

    def test_set_license_flag(self):
        self.assertEqual(classify_comment("// setLicenseFlag(false)"), CommentClass.DEV_COMMENT)

    def test_dot_license_property(self):
        self.assertEqual(classify_comment("// config.license is optional"), CommentClass.DEV_COMMENT)

    def test_import_license(self):
        self.assertEqual(classify_comment("// import LicenseValidator from utils"), CommentClass.DEV_COMMENT)


class TestNoiseClassification(unittest.TestCase):

    def test_todo(self):
        self.assertEqual(classify_comment("// TODO: fix this later"), CommentClass.NOISE)

    def test_fixme(self):
        self.assertEqual(classify_comment("// FIXME: race condition"), CommentClass.NOISE)

    def test_separator_line(self):
        self.assertEqual(classify_comment("// --------------------------------"), CommentClass.NOISE)

    def test_empty_comment(self):
        self.assertEqual(classify_comment("//"), CommentClass.NOISE)

    def test_javadoc_param(self):
        self.assertEqual(classify_comment("// @param name the user name"), CommentClass.NOISE)

    def test_autogenerated(self):
        self.assertEqual(classify_comment("// Auto-generated code. Do not edit."), CommentClass.NOISE)

    def test_vim_directive(self):
        self.assertEqual(classify_comment("// vim: set ts=4 sw=4:"), CommentClass.NOISE)

    def test_empty_string(self):
        self.assertEqual(classify_comment(""), CommentClass.NOISE)

    def test_whitespace_only(self):
        self.assertEqual(classify_comment("   "), CommentClass.NOISE)


class TestEdgeCases(unittest.TestCase):

    def test_license_url_in_comment(self):
        self.assertEqual(classify_comment("// See http://www.apache.org/licenses/LICENSE-2.0"), CommentClass.LICENSE)

    def test_mixed_todo_and_license(self):
        self.assertEqual(classify_comment("// TODO: add SPDX-License-Identifier here"), CommentClass.NOISE)

    def test_multiline_license_fragment(self):
        self.assertEqual(classify_comment("// This software is distributed under the terms of the MIT License"), CommentClass.LICENSE)

    def test_case_insensitivity(self):
        self.assertEqual(classify_comment("// LICENSED UNDER THE MIT LICENSE"), CommentClass.LICENSE)

    def test_hash_comment_license(self):
        self.assertEqual(classify_comment("# Licensed under Apache License 2.0"), CommentClass.LICENSE)


class TestBatchAndFilter(unittest.TestCase):

    def test_classify_batch(self):
        comments = [
            "// SPDX-License-Identifier: MIT",
            "// Initialize cache",
            "// TODO: fix this",
        ]
        results = classify_batch(comments)
        self.assertEqual(len(results), 3)
        self.assertEqual(results[0][1], CommentClass.LICENSE)
        self.assertEqual(results[1][1], CommentClass.DEV_COMMENT)
        self.assertEqual(results[2][1], CommentClass.NOISE)

    def test_filter_license_comments(self):
        comments = [
            "// SPDX-License-Identifier: MIT",
            "// Initialize cache",
            "// TODO: fix",
            "// Licensed under Apache License 2.0",
        ]
        filtered = filter_license_comments(comments)
        self.assertEqual(len(filtered), 2)

    def test_empty_input(self):
        self.assertEqual(classify_batch([]), [])
        self.assertEqual(filter_license_comments([]), [])


if __name__ == "__main__":
    unittest.main()
