#!/bin/bash
# FOSSology installfodeps script
# Copyright (C) 2008 Hewlett-Packard Development Company, L.P.
#
# This script helps you install build and runtime dependencies on a system.
# It is NOT indented to replace package dependencies, it's just a tool to
# make testing the "upstream" build and install process. If you determine
# this script isn't installing something you think it should, consult
# the packaging metadata for the system in question as that is the
# canonical location for such info, then fix it there first and also
# update this file and the INSTALL document.

## Options parsing and setup
# parse options
OPTS=`getopt -o rbeh --long runtime,buildtime,help -n 'installfodeps' -- "$@"`

if [ $? != 0 ]; then
   echo "ERROR: Bad option specified."
   OPTS="--help"
fi

eval set -- "$OPTS"

# if no options then do everything
if [ "$OPTS" = " --" ]; then
   EVERYTHING=1
fi

while true; do
   case "$1" in
      -r|--runtime) RUNTIME=1; shift;;
      -b|--buildtime) BUILDTIME=1; shift;;
      -e|--everything) EVERYTHING=1; shift;;
      -h|--help)
         echo "Usage: installfodeps [options]";
	 echo "  -r or --runtime    : agent specific actions"
	 echo "  -b or --buildtime  : database specific actions"
	 echo "  -e or --everything : all actions (default)"
	 echo "  -h or --help       : this help text"
	 exit;;
      --) shift; break;;
      *) echo "ERROR: option $1 not recognised"; exit 1;;
   esac
done

if [ $EVERYTHING ]; then
   echo "*** Installing both runtime and buildtime dependencies ***"
   RUNTIME=1
   BUILDTIME=1
fi

# This must run as root.
if [ `id -u` != "0" ] ; then
   echo "ERROR: installfodeps must run as root."
   echo "Aborting."
   #exit 1
fi

# figure out what distro we're on
DISTRO=`lsb_release -is`
CODENAME=`lsb_release -cs`

if [ "$?" != "0" ]; then
   echo "ERROR: this program requires the lsb_release command"
   exit 1
fi

########################################################################

if [ $BUILDTIME ]; then
   case "$DISTRO" in
      Debian)
         echo "Installing Debian buildtime dependencies";
         apt-get install \
            libmagic-dev libxml2-dev libextractor-dev \
            build-essential libtext-template-perl subversion;
         case "$CODENAME" in
            etch) apt-get install postgresql-server-dev-8.1;;
            lenny) apt-get install postgresql-server-dev-8.3;;
            sid) apt-get install postgresql-server-dev-8.3;;
         esac
         ;;
      Fedora)
         echo "Congrats, you get to fix this for Fedora!";
         ;;
      *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
   esac
fi

########################################################################

if [ $RUNTIME ]; then
   case "$DISTRO" in
      Debian)
         echo "Installing Debian runtime dependencies";
         apt-get install \
            apache2 \
            php5 php5-pgsql php-pear libapache2-mod-php5 \
            libmagic1 libxml2 libextractor1c2a libextractor-plugins \
            binutils bzip2 cabextract cpio sleuthkit mkisofs xpdf-utils \
               rpm tar upx-ucl unrar-free unzip;
         case "$CODENAME" in
            etch) apt-get install postgresql-8.1;;
            lenny) apt-get install postgresql-8.3;;
            sid) apt-get install postgresql-8.3;;
         esac
         ;;
      Fedora)
         echo "Congrats, you get to fix this for Fedora!";
         ;;
      *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
   esac
fi

########################################################################
