#!/bin/bash
#
# Create Sym links in simpleUi dir of sources so that the
# simple ui can run from a source tree.
#


LINKS=`find .. -type f | grep -v svn | grep -v tests | grep -E "(php)$" \
 | grep -v 'simpleUi' | grep -v 'copyright/library.php' \
 | grep -v 'copyright/list.php' \
 | grep -v 'copyright/view.php' | grep -v 'copyright/agent.php' \
 | grep -v 'copyright/oneshot.php' | grep -v 'copyright/hist.php' `

for link in $LINKS
do
	replink=${link#../}
        [ -h ${replink} ] && continue;
	ln -s $link ${replink}
done