#!/bin/bash

# Copyright 2018 Siemens AG
# Author: Gaurav Mishra <mishra.gaurav@siemens.com>
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# This script helps you install build and runtime dependencies on a system.
# It is NOT indented to replace package dependencies, it's just a tool to
# make testing the "upstream" build and install process. If you determine
# this script isn't installing something you think it should, consult
# the packaging metadata for the system in question as that is the
# canonical location for such info, then fix it there first and also
# update this file and the INSTALL document.

sudo mkdir -p /var/local/cache/fossology
sudo chown $(whoami) /var/local/cache/fossology
sudo mkdir -p /srv/fossologyTestRepo
sudo chown $(whoami) /srv/fossologyTestRepo
sudo su postgres -c "echo \"CREATE USER fossy WITH PASSWORD 'fossy' CREATEDB;\"|psql" || true
sudo su postgres -c "echo \"CREATE USER fossologytest WITH CREATEDB LOGIN PASSWORD 'fossologytest';\"|psql" || true
sudo su postgres -c "echo 'CREATE DATABASE fossology' | psql -Ufossy" || true
echo "localhost:*:*:fossy:fossy" >> ~/.pgpass
echo "localhost:*:*:fossologytest:fossologytest" >> ~/.pgpass
chmod 0600 ~/.pgpass
sudo apt-get install -q -y cppcheck
