#!/bin/bash
# SPDX-FileCopyrightText: © Fossology contributors

# SPDX-License-Identifier: FSFAP
#
# cron script for running schemaspy
#
SCHEMSPY_DB_USER=${SCHEMSPY_DB_USER:-fossy}
SCHEMSPY_DB_PASS=${SCHEMSPY_DB_PASS:-fossy}

java -jar /usr/local/bin/schemaSpy_4.1.1.jar -t pgsql \
-cp /usr/local/share/postgresql-8.4-701.jdbc3.jar \
-db fossology -s public -host localhost -u "${SCHEMSPY_DB_USER}" -p "${SCHEMSPY_DB_PASS}" -o /var/www/schemaspy

