# FOSSology Docker Compose file
# Copyright Siemens AG 2016, fabio.huser@siemens.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Recipe for setting up a multi container FOSSology
#              Docker setup with separate Database instance

web:
  build: ..
  environment:
    - FOSSOLOGY_DB_HOST=db
    - FOSSOLOGY_DB_NAME=fossology
    - FOSSOLOGY_DB_USER=fossy
    - FOSSOLOGY_DB_PASSWORD=fossy
  ports:
    - 8081:80
  links:
    - db
db:
  image: postgres
  environment:
    - POSTGRES_DB=fossology
    - POSTGRES_USER=fossy
    - POSTGRES_PASSWORD=fossy
    - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
