# FOSSology Docker Compose file
# Copyright Siemens AG 2016, fabio.huser@siemens.com
# Copyright TNG Technology Consulting GmbH 2016-2017, maximilian.huber@tngtech.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Recipe for setting up a multi container FOSSology
#              Docker setup with separate Database instance
version: '2'
services:

################################################################################
  fossology-base-image:
    build:
      context: ..
      dockerfile: install/docker-compose.Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology
    restart: "no" 
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
    user: fossy
    command: "true"

################################################################################
  fossology-scheduler:
    image: fossology
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    user: fossy
    command: scheduler
    links:
      - fossology-db
    # volumes:
    #   - ./_repository:/srv/fossology/repository/

################################################################################
  fossology-web:
    image: fossology
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - FOSSOLOGY_SCHEDULER_HOST=fossology-scheduler
    user: fossy
    command: web
    ports:
      - 8081:8081
    links:
      - fossology-db
      - fossology-scheduler
    volumes_from:
      - fossology-scheduler
      
################################################################################
  fossology-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
