#!/bin/bash
# FOSSology Easy Install script
# Copyright Siemens AG 2017
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Easy install script for fossology. Goes through the steps on the Fossology wiki
touch / 2>/dev/null || SUDO=sudo
set -e
cd "$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"/..
$SUDO utils/fo-cleanold
make clean
$SUDO utils/fo-installdeps
make
$SUDO make install
$SUDO /usr/local/lib/fossology/fo-postinstall
$SUDO cp install/src-install-apache-example.conf /etc/apache2/sites-available/fossology.conf
$SUDO ln -s /etc/apache2/sites-available/fossology.conf /etc/apache2/sites-enabled/fossology.conf
$SUDO install/scripts/php-conf-fix.sh --overwrite
$SUDO /etc/init.d/apache2 restart
$SUDO /etc/init.d/fossology restart

# open fossology page, if X server is installed
if [ -n ${DISPLAY} ]
then
  xdg-open http://localhost/repo &disown
fi
