# SPDX-FileCopyrightText: © 2013 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

test:
	@echo "src/maintagent/agent_tests: NO TESTS HAVE BEEN WRITTEN"
clean:
	@echo "src/maintagent/agent_tests: NO TESTS HAVE BEEN WRITTEN. Nothing to Clean."
install:
	@echo "src/maintagent/agent_tests: NO TESTS HAVE BEEN WRITTEN. Nothing to install."
uninstall:
	@echo "src/maintagent/agent_tests: NO TESTS HAVE BEEN WRITTEN. Nothing to uninstall."

.PHONY: all test clean install uninstall coverage
