#!/bin/bash
# Copyright Siemens AG 2017
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#

#### start apache2
echo "Starting apache2..."
/etc/init.d/apache2 start

#### start fossology scheduler
echo "Starting fossology scheduler..."
/etc/init.d/fossology start
