#!/bin/bash
# SPDX-FileCopyrightText: © 2017 Siemens AG

# SPDX-License-Identifier: FSFAP

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#### install dependencies
apt-get install -y python3-pip python3.4-venv libyaml-dev
python3 -m venv venv
${DIR}/venv/bin/pip3 install awscli
