#!/bin/sh
# new_wc_pfile_agent
# Copyright (C) 2007 Hewlett-Packard Development Company, L.P.
#  
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

PATH=/usr/local/bin:$PATH
TYPE=wc-pfiles
WORKDIR=/tmp/$TYPE/
GOFILE=$WORKDIR/go
SLEEP=10

rm -fr $WORKDIR
mkdir -p $WORKDIR
touch $GOFILE

while [ -f $GOFILE ]
do
    while args=$(osrbjob claim $TYPE $(hostname -f)-$$)
    do
	eval $args
	PDIR=$WORKDIR/u$job_ufile_fk/jq$jq_pk
	mkdir -p $PDIR
	PF=$PDIR/pfiles
	if osrbjob query $jq_pk > $PF
	then
	    while read pfileid pfilename
	    do
	        set -- $(repcat files $pfilename | wc 2>$PDIR/stderr)
		echo "insert into agent_wc (pfile_fk, wc_words, wc_lines) values ($pfileid, $1, $2);";
	    done < $PF | osrbjob db
	    osrbjob continue $jq_pk
	else
	    osrbjob finish $jq_pk 1 "" ""
	fi
	rm -r $PDIR

	[ -f $GOFILE ] || exit
    done

    sleep $SLEEP
done
