#!/bin/bash
# SPDX-FileCopyrightText: © 2008 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only
#
# Stupid wrapper so cron run is easier
#
thisrun=`date +"%Y-%m-%d"`
#
# Get the storage path
. /usr/local/include/FMDir

if [ "$FMDIR" == "" ]
then
	FMDIR='/tmp'
fi

mkdir -p $FMDIR/Run-logs
/usr/local/bin/GetFM > "$FMDIR/Run-logs/GetFM.log-$thisrun 2>&1"

exit 0

