#!/bin/bash
# Script to get latest FreshMeat RDF file and drive updating the DB
#
# Author: mark.donohoe@hp.com
# Version: $Id: GetFM 1437 2007-11-17 04:37:18Z markd $

# TODO: need to source a file with the correct paths, not hard code them.
# 
# Constants
#
# put known filenames etc....
URL="http://freshmeat.net/backend/fm-projects.rdf.bz2"
#DIR="/srv/fossology/repository/happy/Freshmeat/Rdfs/"

DIR="/srv/fossology/repository/firenze/Freshmeat/"
RDIR="${DIR}Rdfs/"
Wget_Log="${RDIR}wget.log"
INPUTFILES="${DIR}Input-Files/"
RLOGS="${DIR}Run-logs/"
# is the mkdir needed?  ReadMe says to precreate....
mkdir -p $RLOGS

Date=`date +"%Y-%m-%d"`
Compressed_file="fm-projects.rdf-${Date}.bz2"
Uncompressed_file="fm-projects.rdf-${Date}"

# Programs, where on the system shall these be? I think in /usr/local/bin....
# Set the path to find them
export PATH=$PATH:/usr/local/bin:/usr/local/lib

# We need to explicitly export the proxy since crontab does not include
# the shell
export http_proxy="http://web-proxy.fc.hp.com:8088"
#
# get the daily rdf file
echo "will do:"
echo "wget -o $Wget_Log -O $RDIR$Compressed_file $URL"
echo ""

wget -o $Wget_Log -O ${RDIR}$Compressed_file $URL 

top1k="${RDIR}Top1k-${Date}"
echo $top1k > "${RDIR}Current-top1k"
#
# uncompress todays rdf file and call mktop1k to create the top 1000 from this file
#
echo "uncompressing $RDIR$Compressed_file"

bunzip2 -qc $RDIR$Compressed_file > $RDIR$Uncompressed_file
mktop1k -i $RDIR$Uncompressed_file -o $top1k

# Diff the current and previous top 1000 xml files

read < "${RDIR}Previous-top1k" Previous_top1k

current=`cat "${RDIR}Current-top1k"`
previous=`cat "${RDIR}Previous-top1k"`
echo  "Doing..."
echo "diffm $current $previous -o $INPUTFILES"
diffm -f "$current" "$previous" -o "$INPUTFILES" > "${RLOGS}log.diffm.${Date}"
drtn=$?
#echo "diffm returned the following:$drtn"
#
# replace previous rdf with current for the next run.
# May want to make a function cause you might want to clean up old rdf's and top1k's.....
cp ${RDIR}Current-top1k ${RDIR}Previous-top1k

# if diffm returns 0 there is no projects to update, so clean up and stop
if (( $drtn == 0 ))
then
  echo "exiting, nothing to do"
  exit 0
else
# we have something to process, get it and upload what we can.
  echo "Doing...\n"
  echo "get-projects -f ${INPUTFILES}Update.fm.rdf.${Date} > ${RLOGS}log.get-projects.${Date} 2>&1"
  get-projects -f "${INPUTFILES}Update.fm.rdf.${Date} > ${RLOGS}log.get-projects.${Date} 2>&1"
  # upload the files with cp2foss 
  echo "Doing...\n"
  echo "cp2foss -f ${INPUTFILES}FM-projects2update.${Date} > ${RLOGS}log.cp2foss.${Date} 2>&1 &"
#  cp2foss -f "{INPUTFILES}FM-projects2update.${Date} > ${RLOGS}log.cp2foss.${Date} 2>&1 &"
  # echo check the following log files .....
fi
