# SPDX-FileCopyrightText: © 2026 FOSSology contributors
#
# SPDX-License-Identifier: GPL-2.0-only

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: fossology-config
            - secretRef:
                name: fossology-secrets
          env:
            - name: POSTGRES_INITDB_ARGS
              value: -E SQL_ASCII
          readinessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
