# SPDX-FileCopyrightText: © 2026 FOSSology contributors
#
# SPDX-License-Identifier: GPL-2.0-only

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
