# SPDX-FileCopyrightText: © 2026 FOSSology contributors
#
# SPDX-License-Identifier: GPL-2.0-only

apiVersion: v1
kind: Secret
metadata:
  name: fossology-secrets
type: Opaque
stringData:
  FOSSOLOGY_DB_PASSWORD: fossy
  POSTGRES_PASSWORD: fossy
