# SPDX-FileCopyrightText: © 2011 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

# Makefile for nomos UI functional tests
test:
	echo "Make UI Functional Tests"
	@echo "src/nomos/ui_tests/Functional: Tests cannot be run by makefile"
clean:
	@echo "src/nomos/ui_tests/Functional: Nothing to Clean."
install:
	@echo "src/nomos/ui_tests/Functional: Nothing to install."
uninstall:
	@echo "src/nomos/ui_tests/Functional: Nothing to uninstall."

.PHONY: all test clean install uninstall coverage
