# SPDX-FileCopyrightText: © 2013 Hewlett-Packard Development Company, L.P.

# SPDX-License-Identifier: GPL-2.0-only

all:
	@echo "nothing to do"

test:
	@echo "src/maintagent/ui_tests: NO TESTS HAVE BEEN CREATED"

coverage:
	@echo "nothing to do"

clean:
	@echo "src/maintagent/ui_tests: NO TESTS HAVE BEEN CREATED. Nothing to Clean."
install:
	@echo "src/maintagent/ui_tests: NO TESTS HAVE BEEN CREATED. Nothing to install."
uninstall:
	@echo "src/maintagent/ui_tests: NO TESTS HAVE BEEN CREATED. Nothing to uninstall."

.PHONY: all test clean install uninstall coverage
