#!/bin/bash
# new_unpack_agent
# Copyright (C) 2007 Hewlett-Packard Development Company, L.P.
#  
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
PATH=/usr/local/bin:$PATH

WORKDIR=/tmp/unpack/
GOFILE=$WORKDIR/go
SLEEP=10

rm -fr $WORKDIR
mkdir -p $WORKDIR
touch $GOFILE

while [ -f $GOFILE ]
do
    while args=$(osrbjob claim unpack $(hostname -f)-$$)
    do
	eval $args
	# Set all the ARG_ values like engine-shell does
	set -a; eval $(osrbjob query1 $jq_pk); set +a

	PDIR=$WORKDIR/p$job_ufile_fk/jq$jq_pk
	rm -fr $PDIR
	mkdir -p $PDIR/unpack

	#### exec > $PDIR/log.txt 2>&1

	if /usr/local/bin/ununpack -v -qRCQx -d $PDIR/unpack > $PDIR/log 2>&1
	then
	    ### rm -r $PDIR
	    osrbjob finish $jq_pk 1 "" ""
	else
	    osrbjob finish $jq_pk 2 "see $PDIR/log" ""
	fi

	#### exec > $WORKDIR/log.txt 2>&1

	[ -f $GOFILE ] || exit
    done

    sleep $SLEEP
done
