<!-- left nav-->
<!--SOME TWEAKING HAS TO BE DONE THERE TO KEEP BORDER ASPECT ON ALL BR0WSERS-->
<div id="sidebar">
<div class="sidetitle">What's Hot!</div>
<ul class="navibar">
<li><a href="http://www.fossbazaar.org/">FOSSBazaar</a></li>
<li><a href="http://fossology.org/docs/videos">Video Tutorials</a></li>
</ul>
<div class="sidetitle">FOSSology</div>
<ul class="navibar">
<li><a href="/">Home</a></li>
<li><a href="http://fossology.org/docs/about_us">About FOSSology</a></li>
<li><a href="http://fossology.org/docs/live_demo">Live Demo</a></li>
<li><a href="http://fossology.org/docs/contact_us">Contact us</a></li>
<li><a href="http://fossology.org/docs/links_-_related_projects">Links - Related Projects</a></li>
</ul>
<div class="sidetitle">User Resources</div>
<ul class="navibar">
<li><a href="http://fossology.org/docs/link_to_source_download_at_sourceforge.net">Download</a></li>
<li><a href="http://fossology.org/docs/contact_us">Mailing Lists</a></li>
<li><a href="http://fossology.org/docs/frequently_asked_questions">FAQ</a></li>
<li><a href="http://fossology.org/docs/videos">Screenshots</a></li>
<li><a href="http://fossology.org/docs/release_notes">Release Notes</a></li>
<li><a href="http://fossology.org/docs/">User Docs</a></li>
</ul>
<div class="sidetitle">Developer Resources</div>
<ul class="navibar">
<li><a href="http://fossology.org/docs/development_status">Development Status</a></li>
<li><a href="http://fossology.org/docs/link_to_source_download_at_sourceforge.net">Source Code</a></li>
<li><a href="http://fossology.org/docs/#developer_documentation">Developer Docs</a></li>
<li><a href="http://fossology.org/docs/contributing">Contributing</a></li>
<li><a href="http://fossology.org/docs/legal_info">License</a></li>
<li><a href="http://fossology.org/docs/start?do=logout">Login</a></li>
</ul>
</div>
