<body  bgcolor="#ffffff">
<!-- left nav-->
<!--SOME TWEAKING HAS TO BE DONE THERE TO KEEP BORDER ASPECT ON ALL BR0WSERS-->
<div id="sidebar">
<div class="sidetitle">FOSSOLOGY</div>
<ul class="navibar">
<li><a href="/">Home</a><br>
<li><a href="http://fossology.org/docs/about_us">About FOSSology</a><br>
<li><a href="http://repo.fossology.org">Demo - Try it!</a><br>
<li><a href="http://fossology.org/docs/contact_us">Contact us</a><br>
<li><a href="http://fossology.org/docs/links_-_related_projects">Links - Related Projects</a><br>
</ul>
<P>
<div class="sidetitle">USER RESOURCES</div>
<ul class="navibar">
<li><a href="http://fossology.org/docs/link_to_source_download_at_sourceforge.net">Download</a>
<li><a href="http://fossology.org/docs/contact_us">Mailing Lists</a>
<li><a href="http://fossology.org/docs/frequently_asked_questions">FAQ</a>
<li><a href="">Screenshots</a>
<li><a href="http://fossology.org/docs/release_notes">Release Notes</a>
<li><a href="http://fossology.org/docs/">User Docs</a>
</ul>
<P>
<div class="sidetitle">DEVELOPER RESOURCES</div>
<ul class="navibar">
<li><a href="http://fossology.org/docs/development_status">Development Status</a>
<li><a href="http://fossology.org/docs/link_to_source_download_at_sourceforge.net">Source Code</a>
<li><a href="http://fossology.org/docs/#developer_documentation">Developer Docs</a>
<li><a href="http://fossology.org/docs/contributing">Bug Reporting</a>
<li><a href="http://fossology.org/docs/legal_info">License</a>
<li><a href="http://fossology.org/docs/start?do=logout">Login</a>
</ul>
</div>
