<TABLE border="0" cellpadding="0" cellspacing="0" width="100%">
  <TR>
    <TD align="center" class="sidebar-width"><IMG SRC="http://fossology.org/fossology_logo.png" ALT="FOSSology Project Logo">
    <TD class="sidebar-gutter-width">
    <TD><H2>The FOSSology Project</h2>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<tt><b>FOSS:</b></tt>  Free (as in Freedom) Open Source Software
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<tt><b>-ology:</b></tt> the study of
  </TR>
</TABLE>
